![](images/header_05.png)<br>

<hr style="border-width: 3px;">

# Encuesta de desarrolladores 2018 de Stack Overflow


## Comprensión de los datos


### <span style="color:#313f9e; font-weight: bold;">Recolección inicial de datos:</span>
Los datos que emplearemos en este proyecto están disponibles en el sitio de Kaggle ([Datos](shttps://www.kaggle.com/stackoverflow/stack-overflow-2018-developer-survey/data)).


### <span style="color:#313f9e; font-weight: bold;">Descripción de los datos:</span>
El conjunto de datos contiene 2 tablas en un archivo comprimido [stack-overflow-2018-developer-survey.zip](https://www.kaggle.com/stackoverflow/stack-overflow-2018-developer-survey/downloads/stack-overflow-2018-developer-survey.zip/2).

El archivo <code>survey_results_public.csv</code> contiene las respuestas de los usuarios a la encuesta y presenta la siguiente estructura:

In [1]:
"""
Reconocimiento de patrones: Comprensión de los datos
"""

import pandas as pd
import numpy as np

In [2]:
path = "Data sets/Stack Overflow Survey/"
df = pd.read_csv(path + "survey_results_public.csv")

print(df.info())

/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3044: DtypeWarning: Columns (8,12,13,14,15,16,50,51,52,53,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98855 entries, 0 to 98854
Columns: 129 entries, Respondent to SurveyEasy
dtypes: float64(41), int64(1), object(87)
memory usage: 97.3+ MB
None


La información que obtenemos establece que:
<ol>
<li>El objeto Dataframe resultante tiene 98855 renglones, cuyos ínidices (las llaves en el Dataframe) van de 0 a 98854.</li>
<li>Los datos vienen descritos por 129 columnas, siendo la primea <code>Respondent</code> y la última <code>SurveyEasy</code>.</li>
<li>Pandas encontró 3 tipos de datos en la tabla: 41 columnas identificadas como <code>float64</code>, 1 columna identificada como <code>int64</code> y 87 columnas identificadas como <code>object</code>.<br>Hay que notar que pandas intenta "adivinar" el tipo de dato de cada columna; el mensaje de advertencia corresponde a renglones cuyo tipo no pudo adivinar. </li>
<li>El objeto Dataframe utiliza más de <code>97.3MB</code>.</li>
<li>El método regresa <code>None</code>.</li>
</ol>
<br>

<div style="width:10%; float:left; padding-right:5px; color:#e62e00; font-weight: bold;
text-align:right;">
Nota:
</div>
<div style="margin-left: 10%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
El warning ocurre porque, en las columnas que contienen datos mezclados (77/129), resulta más difícil para el sistema "adivinar" el tipo de dato. El problema se resuelve haciendo:<br>
<code style="background-color:#f7f7f7;">df = pd.read_csv(path + "survey_results_public.csv", low_memory=False)</code><br>como sugiere el mensaje. Sin embargo, el mensaje parece ser obsoleto, por lo que en realidad no afecta el desempeño.
</div>

El archivo <code>survey_results_schema.csv</code>, por otra parte, contiene una tabla con los nombres de las columnas y la pregunta correspondiente en la encuesta: 

In [3]:
dfQ = pd.read_csv(path + "survey_results_schema.csv")

print(dfQ.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129 entries, 0 to 128
Data columns (total 2 columns):
Column          129 non-null object
QuestionText    129 non-null object
dtypes: object(2)
memory usage: 2.1+ KB
None


Los datos en esta tabla son:<br>

<table style="width: 90%">
<col width="8%">
<col width="30%">

<tr><th style="text-align: left; font-size: 110%; border: 1px solid #555;">ID</th>
<th style="text-align: left; font-size: 110%; border: 1px solid #555;">Column</th>
<th style="text-align: left; font-size: 110%; border: 1px solid #555;">QuestionText</th></tr>
<tr><td style="text-align: left; border: 1px solid #555;">1</td><td style="text-align: left; border: 1px solid #555;">Respondent</td><td style="text-align: left; border: 1px solid #555;">Randomized respondent ID number (not in order of survey response time)</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">2</td><td style="text-align: left; border: 1px solid #555;">Hobby</td><td style="text-align: left; border: 1px solid #555;">Do you code as a hobby?</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">3</td><td style="text-align: left; border: 1px solid #555;">OpenSource</td><td style="text-align: left; border: 1px solid #555;">Do you contribute to open source projects?</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">4</td><td style="text-align: left; border: 1px solid #555;">Country</td><td style="text-align: left; border: 1px solid #555;">In which country do you currently reside?</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">5</td><td style="text-align: left; border: 1px solid #555;">Student</td><td style="text-align: left; border: 1px solid #555;">"Are you currently enrolled in a formal, degree-granting college or university program?"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">6</td><td style="text-align: left; border: 1px solid #555;">Employment</td><td style="text-align: left; border: 1px solid #555;">Which of the following best describes your current employment status?</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">7</td><td style="text-align: left; border: 1px solid #555;">FormalEducation</td><td style="text-align: left; border: 1px solid #555;">Which of the following best describes the highest level of formal education that you’ve completed?</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">8</td><td style="text-align: left; border: 1px solid #555;">UndergradMajor</td><td style="text-align: left; border: 1px solid #555;">You previously indicated that you went to a college or university. Which of the following best describes your main field of study (aka 'major')</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">9</td><td style="text-align: left; border: 1px solid #555;">CompanySize</td><td style="text-align: left; border: 1px solid #555;">Approximately how many people are employed by the company or organization you work for?</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">10</td><td style="text-align: left; border: 1px solid #555;">DevType</td><td style="text-align: left; border: 1px solid #555;">Which of the following describe you? Please select all that apply.</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">11</td><td style="text-align: left; border: 1px solid #555;">YearsCoding</td><td style="text-align: left; border: 1px solid #555;">"Including any education, for how many years have you been coding?"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">12</td><td style="text-align: left; border: 1px solid #555;">YearsCodingProf</td><td style="text-align: left; border: 1px solid #555;">For how many years have you coded professionally (as a part of your work)?</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">13</td><td style="text-align: left; border: 1px solid #555;">JobSatisfaction</td><td style="text-align: left; border: 1px solid #555;">"How satisfied are you with your current job? If you work more than one job, please answer regarding the one you spend the most hours on."</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">14</td><td style="text-align: left; border: 1px solid #555;">CareerSatisfaction</td><td style="text-align: left; border: 1px solid #555;">"Overall, how satisfied are you with your career thus far?"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">15</td><td style="text-align: left; border: 1px solid #555;">HopeFiveYears</td><td style="text-align: left; border: 1px solid #555;">Which of the following best describes what you hope to be doing in five years?</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">16</td><td style="text-align: left; border: 1px solid #555;">JobSearchStatus</td><td style="text-align: left; border: 1px solid #555;">Which of the following best describes your current job-seeking status?</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">17</td><td style="text-align: left; border: 1px solid #555;">LastNewJob</td><td style="text-align: left; border: 1px solid #555;">When was the last time that you took a job with a new employer?</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">18</td><td style="text-align: left; border: 1px solid #555;">AssessJob1</td><td style="text-align: left; border: 1px solid #555;">"Imagine that you are assessing a potential job opportunity. Please rank the following aspects of the job opportunity in order of importance (by dragging the choices up and down), where 1 is the most important and 10 is the least important. The industry that I'd be working in"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">19</td><td style="text-align: left; border: 1px solid #555;">AssessJob2</td><td style="text-align: left; border: 1px solid #555;">"Imagine that you are assessing a potential job opportunity. Please rank the following aspects of the job opportunity in order of importance (by dragging the choices up and down), where 1 is the most important and 10 is the least important. The financial performance or funding status of the company or organization"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">20</td><td style="text-align: left; border: 1px solid #555;">AssessJob3</td><td style="text-align: left; border: 1px solid #555;">"Imagine that you are assessing a potential job opportunity. Please rank the following aspects of the job opportunity in order of importance (by dragging the choices up and down), where 1 is the most important and 10 is the least important. The specific department or team I'd be working on"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">21</td><td style="text-align: left; border: 1px solid #555;">AssessJob4</td><td style="text-align: left; border: 1px solid #555;">"Imagine that you are assessing a potential job opportunity. Please rank the following aspects of the job opportunity in order of importance (by dragging the choices up and down), where 1 is the most important and 10 is the least important. The languages, frameworks, and other technologies I'd be working with"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">22</td><td style="text-align: left; border: 1px solid #555;">AssessJob5</td><td style="text-align: left; border: 1px solid #555;">"Imagine that you are assessing a potential job opportunity. Please rank the following aspects of the job opportunity in order of importance (by dragging the choices up and down), where 1 is the most important and 10 is the least important. The compensation and benefits offered"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">23</td><td style="text-align: left; border: 1px solid #555;">AssessJob6</td><td style="text-align: left; border: 1px solid #555;">"Imagine that you are assessing a potential job opportunity. Please rank the following aspects of the job opportunity in order of importance (by dragging the choices up and down), where 1 is the most important and 10 is the least important. The office environment or company culture"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">24</td><td style="text-align: left; border: 1px solid #555;">AssessJob7</td><td style="text-align: left; border: 1px solid #555;">"Imagine that you are assessing a potential job opportunity. Please rank the following aspects of the job opportunity in order of importance (by dragging the choices up and down), where 1 is the most important and 10 is the least important. The opportunity to work from home/remotely"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">25</td><td style="text-align: left; border: 1px solid #555;">AssessJob8</td><td style="text-align: left; border: 1px solid #555;">"Imagine that you are assessing a potential job opportunity. Please rank the following aspects of the job opportunity in order of importance (by dragging the choices up and down), where 1 is the most important and 10 is the least important. Opportunities for professional development"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">26</td><td style="text-align: left; border: 1px solid #555;">AssessJob9</td><td style="text-align: left; border: 1px solid #555;">"Imagine that you are assessing a potential job opportunity. Please rank the following aspects of the job opportunity in order of importance (by dragging the choices up and down), where 1 is the most important and 10 is the least important. The diversity of the company or organization"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">27</td><td style="text-align: left; border: 1px solid #555;">AssessJob10</td><td style="text-align: left; border: 1px solid #555;">"Imagine that you are assessing a potential job opportunity. Please rank the following aspects of the job opportunity in order of importance (by dragging the choices up and down), where 1 is the most important and 10 is the least important. How widely used or impactful the product or service I'd be working on is"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">28</td><td style="text-align: left; border: 1px solid #555;">AssessBenefits1</td><td style="text-align: left; border: 1px solid #555;">"Now, imagine you are assessing a job's benefits package. Please rank the following aspects of a job's benefits package from most to least important to you (by dragging the choices up and down), where 1 is most important and 11 is least important. Salary and/or bonuses"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">29</td><td style="text-align: left; border: 1px solid #555;">AssessBenefits2</td><td style="text-align: left; border: 1px solid #555;">"Now, imagine you are assessing a job's benefits package. Please rank the following aspects of a job's benefits package from most to least important to you (by dragging the choices up and down), where 1 is most important and 11 is least important. Stock options or shares"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">30</td><td style="text-align: left; border: 1px solid #555;">AssessBenefits3</td><td style="text-align: left; border: 1px solid #555;">"Now, imagine you are assessing a job's benefits package. Please rank the following aspects of a job's benefits package from most to least important to you (by dragging the choices up and down), where 1 is most important and 11 is least important. Health insurance"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">31</td><td style="text-align: left; border: 1px solid #555;">AssessBenefits4</td><td style="text-align: left; border: 1px solid #555;">"Now, imagine you are assessing a job's benefits package. Please rank the following aspects of a job's benefits package from most to least important to you (by dragging the choices up and down), where 1 is most important and 11 is least important. Parental leave"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">32</td><td style="text-align: left; border: 1px solid #555;">AssessBenefits5</td><td style="text-align: left; border: 1px solid #555;">"Now, imagine you are assessing a job's benefits package. Please rank the following aspects of a job's benefits package from most to least important to you (by dragging the choices up and down), where 1 is most important and 11 is least important. Fitness or wellness benefit (ex. gym membership, nutritionist)"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">33</td><td style="text-align: left; border: 1px solid #555;">AssessBenefits6</td><td style="text-align: left; border: 1px solid #555;">"Now, imagine you are assessing a job's benefits package. Please rank the following aspects of a job's benefits package from most to least important to you (by dragging the choices up and down), where 1 is most important and 11 is least important. Retirement or pension savings matching"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">34</td><td style="text-align: left; border: 1px solid #555;">AssessBenefits7</td><td style="text-align: left; border: 1px solid #555;">"Now, imagine you are assessing a job's benefits package. Please rank the following aspects of a job's benefits package from most to least important to you (by dragging the choices up and down), where 1 is most important and 11 is least important. Company-provided meals or snacks"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">35</td><td style="text-align: left; border: 1px solid #555;">AssessBenefits8</td><td style="text-align: left; border: 1px solid #555;">"Now, imagine you are assessing a job's benefits package. Please rank the following aspects of a job's benefits package from most to least important to you (by dragging the choices up and down), where 1 is most important and 11 is least important. Computer/office equipment allowance"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">36</td><td style="text-align: left; border: 1px solid #555;">AssessBenefits9</td><td style="text-align: left; border: 1px solid #555;">"Now, imagine you are assessing a job's benefits package. Please rank the following aspects of a job's benefits package from most to least important to you (by dragging the choices up and down), where 1 is most important and 11 is least important. Childcare benefit"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">37</td><td style="text-align: left; border: 1px solid #555;">AssessBenefits10</td><td style="text-align: left; border: 1px solid #555;">"Now, imagine you are assessing a job's benefits package. Please rank the following aspects of a job's benefits package from most to least important to you (by dragging the choices up and down), where 1 is most important and 11 is least important. Transportation benefit (ex. company-provided transportation, public transit allowance)"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">38</td><td style="text-align: left; border: 1px solid #555;">AssessBenefits11</td><td style="text-align: left; border: 1px solid #555;">"Now, imagine you are assessing a job's benefits package. Please rank the following aspects of a job's benefits package from most to least important to you (by dragging the choices up and down), where 1 is most important and 11 is least important. Conference or education budget"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">39</td><td style="text-align: left; border: 1px solid #555;">JobContactPriorities1</td><td style="text-align: left; border: 1px solid #555;">"Imagine that a company wanted to contact you about a job that is a good fit for you. Please rank your preference in how you are contacted (by dragging the choices up and down), where 1 is the most preferred and 5 is the least preferred. Telephone call"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">40</td><td style="text-align: left; border: 1px solid #555;">JobContactPriorities2</td><td style="text-align: left; border: 1px solid #555;">"Imagine that a company wanted to contact you about a job that is a good fit for you. Please rank your preference in how you are contacted (by dragging the choices up and down), where 1 is the most preferred and 5 is the least preferred. Email to my private address"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">41</td><td style="text-align: left; border: 1px solid #555;">JobContactPriorities3</td><td style="text-align: left; border: 1px solid #555;">"Imagine that a company wanted to contact you about a job that is a good fit for you. Please rank your preference in how you are contacted (by dragging the choices up and down), where 1 is the most preferred and 5 is the least preferred. Email to my work address"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">42</td><td style="text-align: left; border: 1px solid #555;">JobContactPriorities4</td><td style="text-align: left; border: 1px solid #555;">"Imagine that a company wanted to contact you about a job that is a good fit for you. Please rank your preference in how you are contacted (by dragging the choices up and down), where 1 is the most preferred and 5 is the least preferred. Message on a job site"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">43</td><td style="text-align: left; border: 1px solid #555;">JobContactPriorities5</td><td style="text-align: left; border: 1px solid #555;">"Imagine that a company wanted to contact you about a job that is a good fit for you. Please rank your preference in how you are contacted (by dragging the choices up and down), where 1 is the most preferred and 5 is the least preferred. Message on a social media site"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">44</td><td style="text-align: left; border: 1px solid #555;">JobEmailPriorities1</td><td style="text-align: left; border: 1px solid #555;">"Imagine that same company decided to contact you through email. Please rank the following items by how important it is to include them in the message (by dragging the choices up and down), where 1 is the most important and 7 is the least important. Details on the company I'd be working for"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">45</td><td style="text-align: left; border: 1px solid #555;">JobEmailPriorities2</td><td style="text-align: left; border: 1px solid #555;">"Imagine that same company decided to contact you through email. Please rank the following items by how important it is to include them in the message (by dragging the choices up and down), where 1 is the most important and 7 is the least important. Details on the specific department I'd be working for or product I'd be working on"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">46</td><td style="text-align: left; border: 1px solid #555;">JobEmailPriorities3</td><td style="text-align: left; border: 1px solid #555;">"Imagine that same company decided to contact you through email. Please rank the following items by how important it is to include them in the message (by dragging the choices up and down), where 1 is the most important and 7 is the least important. Specifics of why they think I'd be a good fit for the role (ex. my prior work history, projects on GitHub)"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">47</td><td style="text-align: left; border: 1px solid #555;">JobEmailPriorities4</td><td style="text-align: left; border: 1px solid #555;">"Imagine that same company decided to contact you through email. Please rank the following items by how important it is to include them in the message (by dragging the choices up and down), where 1 is the most important and 7 is the least important. Details of which technologies I'd be working with"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">48</td><td style="text-align: left; border: 1px solid #555;">JobEmailPriorities5</td><td style="text-align: left; border: 1px solid #555;">"Imagine that same company decided to contact you through email. Please rank the following items by how important it is to include them in the message (by dragging the choices up and down), where 1 is the most important and 7 is the least important. An estimate of the compensation range"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">49</td><td style="text-align: left; border: 1px solid #555;">JobEmailPriorities6</td><td style="text-align: left; border: 1px solid #555;">"Imagine that same company decided to contact you through email. Please rank the following items by how important it is to include them in the message (by dragging the choices up and down), where 1 is the most important and 7 is the least important. Information on the company's hiring process"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">50</td><td style="text-align: left; border: 1px solid #555;">JobEmailPriorities7</td><td style="text-align: left; border: 1px solid #555;">"Imagine that same company decided to contact you through email. Please rank the following items by how important it is to include them in the message (by dragging the choices up and down), where 1 is the most important and 7 is the least important. Details on the company's product development process"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">51</td><td style="text-align: left; border: 1px solid #555;">UpdateCV</td><td style="text-align: left; border: 1px solid #555;">"Think back to the last time you updated your resumé, CV, or an online profile on a job site. What is the main reason that you did so?"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">52</td><td style="text-align: left; border: 1px solid #555;">Currency</td><td style="text-align: left; border: 1px solid #555;">"Which currency do you use day-to-day? If your answer is complicated, please pick the one you're most comfortable estimating in."</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">53</td><td style="text-align: left; border: 1px solid #555;">Salary</td><td style="text-align: left; border: 1px solid #555;">"What is your current gross salary (before taxes and deductions), in ...? Please enter a whole number in the box below, without any punctuation. If you are paid hourly, please estimate an equivalent weekly, monthly, or yearly salary. If you prefer not to answer, please leave the box empty."</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">54</td><td style="text-align: left; border: 1px solid #555;">SalaryType</td><td style="text-align: left; border: 1px solid #555;">"Is that salary weekly, monthly, or yearly?"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">55</td><td style="text-align: left; border: 1px solid #555;">ConvertedSalary</td><td style="text-align: left; border: 1px solid #555;">"Salary converted to annual USD salaries using the exchange rate on 2018-01-18, assuming 12 working months and 50 working weeks."</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">56</td><td style="text-align: left; border: 1px solid #555;">CurrencySymbol</td><td style="text-align: left; border: 1px solid #555;">Three digit currency abbreviation.</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">57</td><td style="text-align: left; border: 1px solid #555;">CommunicationTools</td><td style="text-align: left; border: 1px solid #555;">"Which of the following tools do you use to communicate, coordinate, or share knowledge with your coworkers? Please select all that apply."</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">58</td><td style="text-align: left; border: 1px solid #555;">TimeFullyProductive</td><td style="text-align: left; border: 1px solid #555;">"Suppose a new developer with four years of experience, including direct experience working with your company's main technical stack, joined your team tomorrow.  All other things being equal, how long would you expect it to take before they were fully productive and contributing at a typical level to your main code base?"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">59</td><td style="text-align: left; border: 1px solid #555;">EducationTypes</td><td style="text-align: left; border: 1px solid #555;">Which of the following types of non-degree education have you used or participated in? Please select all that apply.</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">60</td><td style="text-align: left; border: 1px solid #555;">SelfTaughtTypes</td><td style="text-align: left; border: 1px solid #555;">"You indicated that you had taught yourself a programming technology without taking a course. What resources did you use to do that? If you’ve done it more than once, please think about the most recent time you’ve done so. Please select all that apply."</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">61</td><td style="text-align: left; border: 1px solid #555;">TimeAfterBootcamp</td><td style="text-align: left; border: 1px solid #555;">You indicated previously that you went through a developer training program or bootcamp. How long did it take you to get a full-time job as a developer after graduating?</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">62</td><td style="text-align: left; border: 1px solid #555;">HackathonReasons</td><td style="text-align: left; border: 1px solid #555;">You indicated previously that you had participated in an online coding competition or hackathon.  Which of the following best describe your reasons for doing so?</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">63</td><td style="text-align: left; border: 1px solid #555;">AgreeDisagree1</td><td style="text-align: left; border: 1px solid #555;">To what extent do you agree or disagree with each of the following statements? I feel a sense of kinship or connection to other developers</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">64</td><td style="text-align: left; border: 1px solid #555;">AgreeDisagree2</td><td style="text-align: left; border: 1px solid #555;">To what extent do you agree or disagree with each of the following statements? I think of myself as competing with my peers</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">65</td><td style="text-align: left; border: 1px solid #555;">AgreeDisagree3</td><td style="text-align: left; border: 1px solid #555;">To what extent do you agree or disagree with each of the following statements? I'm not as good at programming as most of my peers</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">66</td><td style="text-align: left; border: 1px solid #555;">LanguageWorkedWith</td><td style="text-align: left; border: 1px solid #555;">"Which of the following programming, scripting, and markup languages have you done extensive development work in over the past year, and which do you want to work in over the next year?  (If you both worked with the language and want to continue to do so, please check both boxes in that row.)"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">67</td><td style="text-align: left; border: 1px solid #555;">LanguageDesireNextYear</td><td style="text-align: left; border: 1px solid #555;">"Which of the following programming, scripting, and markup languages have you done extensive development work in over the past year, and which do you want to work in over the next year?  (If you both worked with the language and want to continue to do so, please check both boxes in that row.)"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">68</td><td style="text-align: left; border: 1px solid #555;">DatabaseWorkedWith</td><td style="text-align: left; border: 1px solid #555;">"Which of the following database environments have you done extensive development work in over the past year, and which do you want to work in over the next year?   (If you both worked with the database and want to continue to do so, please check both boxes in that row.)"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">69</td><td style="text-align: left; border: 1px solid #555;">DatabaseDesireNextYear</td><td style="text-align: left; border: 1px solid #555;">"Which of the following database environments have you done extensive development work in over the past year, and which do you want to work in over the next year?   (If you both worked with the database and want to continue to do so, please check both boxes in that row.)"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">70</td><td style="text-align: left; border: 1px solid #555;">PlatformWorkedWith</td><td style="text-align: left; border: 1px solid #555;">"Which of the following platforms have you done extensive development work for over the past year?   (If you both developed for the platform and want to continue to do so, please check both boxes in that row.)"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">71</td><td style="text-align: left; border: 1px solid #555;">PlatformDesireNextYear</td><td style="text-align: left; border: 1px solid #555;">"Which of the following platforms have you done extensive development work for over the past year?   (If you both developed for the platform and want to continue to do so, please check both boxes in that row.)"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">72</td><td style="text-align: left; border: 1px solid #555;">FrameworkWorkedWith</td><td style="text-align: left; border: 1px solid #555;">"Which of the following libraries, frameworks, and tools have you done extensive development work in over the past year, and which do you want to work in over the next year?"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">73</td><td style="text-align: left; border: 1px solid #555;">FrameworkDesireNextYear</td><td style="text-align: left; border: 1px solid #555;">"Which of the following libraries, frameworks, and tools have you done extensive development work in over the past year, and which do you want to work in over the next year?"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">74</td><td style="text-align: left; border: 1px solid #555;">IDE</td><td style="text-align: left; border: 1px solid #555;">Which development environment(s) do you use regularly?  Please check all that apply.</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">75</td><td style="text-align: left; border: 1px solid #555;">OperatingSystem</td><td style="text-align: left; border: 1px solid #555;">What is the primary operating system in which you work?</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">76</td><td style="text-align: left; border: 1px solid #555;">NumberMonitors</td><td style="text-align: left; border: 1px solid #555;">How many monitors are set up at your workstation?</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">77</td><td style="text-align: left; border: 1px solid #555;">Methodology</td><td style="text-align: left; border: 1px solid #555;">Which of the following methodologies do you have experience working in?</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">78</td><td style="text-align: left; border: 1px solid #555;">VersionControl</td><td style="text-align: left; border: 1px solid #555;">What version control systems do you use regularly? Please select all that apply.</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">79</td><td style="text-align: left; border: 1px solid #555;">CheckInCode</td><td style="text-align: left; border: 1px solid #555;">"Over the last year, how often have you checked-in or committed code?"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">80</td><td style="text-align: left; border: 1px solid #555;">AdBlocker</td><td style="text-align: left; border: 1px solid #555;">Do you have ad-blocking software installed on any computers you use regularly?</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">81</td><td style="text-align: left; border: 1px solid #555;">AdBlockerDisable</td><td style="text-align: left; border: 1px solid #555;">"In the past month, have you disabled your ad blocker for any reason, even temporarily or for a specific website?"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">82</td><td style="text-align: left; border: 1px solid #555;">AdBlockerReasons</td><td style="text-align: left; border: 1px solid #555;">What are the reasons that you have disabled your ad blocker in the past month? Please select all that apply.</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">83</td><td style="text-align: left; border: 1px solid #555;">AdsAgreeDisagree1</td><td style="text-align: left; border: 1px solid #555;">To what extent do you agree or disagree with the following statements: Online advertising can be valuable when it is relevant to me</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">84</td><td style="text-align: left; border: 1px solid #555;">AdsAgreeDisagree2</td><td style="text-align: left; border: 1px solid #555;">To what extent do you agree or disagree with the following statements: I enjoy seeing online updates from companies that I like</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">85</td><td style="text-align: left; border: 1px solid #555;">AdsAgreeDisagree3</td><td style="text-align: left; border: 1px solid #555;">To what extent do you agree or disagree with the following statements: I fundamentally dislike the concept of advertising</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">86</td><td style="text-align: left; border: 1px solid #555;">AdsActions</td><td style="text-align: left; border: 1px solid #555;">Which of the following actions have you taken in the past month? Please select all that apply.</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">87</td><td style="text-align: left; border: 1px solid #555;">AdsPriorities1</td><td style="text-align: left; border: 1px solid #555;">"Please rank the following advertising qualities in order of their importance to you (by dragging the choices up and down), where 1 is the most important, and 7 is the least important. The advertisement is relevant to me"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">88</td><td style="text-align: left; border: 1px solid #555;">AdsPriorities2</td><td style="text-align: left; border: 1px solid #555;">"Please rank the following advertising qualities in order of their importance to you (by dragging the choices up and down), where 1 is the most important, and 7 is the least important. The advertisement is honest about its goals"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">89</td><td style="text-align: left; border: 1px solid #555;">AdsPriorities3</td><td style="text-align: left; border: 1px solid #555;">"Please rank the following advertising qualities in order of their importance to you (by dragging the choices up and down), where 1 is the most important, and 7 is the least important. The advertisement provides useful information"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">90</td><td style="text-align: left; border: 1px solid #555;">AdsPriorities4</td><td style="text-align: left; border: 1px solid #555;">"Please rank the following advertising qualities in order of their importance to you (by dragging the choices up and down), where 1 is the most important, and 7 is the least important. The advertisement seems trustworthy"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">91</td><td style="text-align: left; border: 1px solid #555;">AdsPriorities5</td><td style="text-align: left; border: 1px solid #555;">"Please rank the following advertising qualities in order of their importance to you (by dragging the choices up and down), where 1 is the most important, and 7 is the least important. The advertisement is from a company that I like"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">92</td><td style="text-align: left; border: 1px solid #555;">AdsPriorities6</td><td style="text-align: left; border: 1px solid #555;">"Please rank the following advertising qualities in order of their importance to you (by dragging the choices up and down), where 1 is the most important, and 7 is the least important. The advertisement offers something of value, like a free trial"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">93</td><td style="text-align: left; border: 1px solid #555;">AdsPriorities7</td><td style="text-align: left; border: 1px solid #555;">"Please rank the following advertising qualities in order of their importance to you (by dragging the choices up and down), where 1 is the most important, and 7 is the least important. The advertisement avoids fluffy or vague language"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">94</td><td style="text-align: left; border: 1px solid #555;">AIDangerous</td><td style="text-align: left; border: 1px solid #555;">What do you think is the most dangerous aspect of increasingly advanced AI technology?</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">95</td><td style="text-align: left; border: 1px solid #555;">AIInteresting</td><td style="text-align: left; border: 1px solid #555;">What do you think is the most exciting aspect of increasingly advanced AI technology?</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">96</td><td style="text-align: left; border: 1px solid #555;">AIResponsible</td><td style="text-align: left; border: 1px solid #555;">"Whose responsibility is it, <u>primarily</u>, to consider the ramifications of increasingly advanced AI technology?"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">97</td><td style="text-align: left; border: 1px solid #555;">AIFuture</td><td style="text-align: left; border: 1px solid #555;">"Overall, what's your take on the future of artificial intelligence?"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">98</td><td style="text-align: left; border: 1px solid #555;">EthicsChoice</td><td style="text-align: left; border: 1px solid #555;">Imagine that you were asked to write code for a purpose or product that you consider extremely unethical. Do you write the code anyway?</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">99</td><td style="text-align: left; border: 1px solid #555;">EthicsReport</td><td style="text-align: left; border: 1px solid #555;">Do you report or otherwise call out the unethical code in question?</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">100</td><td style="text-align: left; border: 1px solid #555;">EthicsResponsible</td><td style="text-align: left; border: 1px solid #555;">Who do you believe is ultimately most responsible for code that accomplishes something unethical?</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">101</td><td style="text-align: left; border: 1px solid #555;">EthicalImplications</td><td style="text-align: left; border: 1px solid #555;">Do you believe that you have an obligation to consider the ethical implications of the code that you write?</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">102</td><td style="text-align: left; border: 1px solid #555;">StackOverflowRecommend</td><td style="text-align: left; border: 1px solid #555;">How likely is it that you would recommend Stack Overflow overall to a friend or colleague? Where 0 is not likely at all and 10 is very likely.</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">103</td><td style="text-align: left; border: 1px solid #555;">StackOverflowVisit</td><td style="text-align: left; border: 1px solid #555;">How frequently would you say you visit Stack Overflow?</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">104</td><td style="text-align: left; border: 1px solid #555;">StackOverflowHasAccount</td><td style="text-align: left; border: 1px solid #555;">Do you have a Stack Overflow account?</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">105</td><td style="text-align: left; border: 1px solid #555;">StackOverflowParticipate</td><td style="text-align: left; border: 1px solid #555;">"How frequently would you say you participate in Q&A on Stack Overflow? By participate we mean ask, answer, vote for, or comment on questions."</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">106</td><td style="text-align: left; border: 1px solid #555;">StackOverflowJobs</td><td style="text-align: left; border: 1px solid #555;">Have you ever used or visited Stack Overflow Jobs?</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">107</td><td style="text-align: left; border: 1px solid #555;">StackOverflowDevStory</td><td style="text-align: left; border: 1px solid #555;">Do you have an up-to-date Developer Story on Stack Overflow?</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">108</td><td style="text-align: left; border: 1px solid #555;">StackOverflowJobsRecommend</td><td style="text-align: left; border: 1px solid #555;">How likely is it that you would recommend Stack Overflow Jobs to a friend or colleague? Where 0 is not likely at all and 10 is very likely.</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">109</td><td style="text-align: left; border: 1px solid #555;">StackOverflowConsiderMember</td><td style="text-align: left; border: 1px solid #555;">Do you consider yourself a member of the Stack Overflow community?</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">110</td><td style="text-align: left; border: 1px solid #555;">HypotheticalTools1</td><td style="text-align: left; border: 1px solid #555;">"Please rate your interest in participating in each of the following hypothetical tools on Stack Overflow, where 1 is not at all interested and 5 is extremely interested. A peer mentoring system"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">111</td><td style="text-align: left; border: 1px solid #555;">HypotheticalTools2</td><td style="text-align: left; border: 1px solid #555;">"Please rate your interest in participating in each of the following hypothetical tools on Stack Overflow, where 1 is not at all interested and 5 is extremely interested. A private area for people new to programming"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">112</td><td style="text-align: left; border: 1px solid #555;">HypotheticalTools3</td><td style="text-align: left; border: 1px solid #555;">"Please rate your interest in participating in each of the following hypothetical tools on Stack Overflow, where 1 is not at all interested and 5 is extremely interested. A programming-oriented blog platform"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">113</td><td style="text-align: left; border: 1px solid #555;">HypotheticalTools4</td><td style="text-align: left; border: 1px solid #555;">"Please rate your interest in participating in each of the following hypothetical tools on Stack Overflow, where 1 is not at all interested and 5 is extremely interested. An employer or job review system"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">114</td><td style="text-align: left; border: 1px solid #555;">HypotheticalTools5</td><td style="text-align: left; border: 1px solid #555;">"Please rate your interest in participating in each of the following hypothetical tools on Stack Overflow, where 1 is not at all interested and 5 is extremely interested. An area for Q&A related to career growth"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">115</td><td style="text-align: left; border: 1px solid #555;">WakeTime</td><td style="text-align: left; border: 1px solid #555;">"On days when you work, what time do you typically wake up?"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">116</td><td style="text-align: left; border: 1px solid #555;">HoursComputer</td><td style="text-align: left; border: 1px solid #555;">"On a typical day, how much time do you spend on a desktop or laptop computer?"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">117</td><td style="text-align: left; border: 1px solid #555;">HoursOutside</td><td style="text-align: left; border: 1px solid #555;">"On a typical day, how much time do you spend outside?"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">118</td><td style="text-align: left; border: 1px solid #555;">SkipMeals</td><td style="text-align: left; border: 1px solid #555;">"In a typical week, how many times do you skip a meal in order to be more productive?"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">119</td><td style="text-align: left; border: 1px solid #555;">ErgonomicDevices</td><td style="text-align: left; border: 1px solid #555;">What ergonomic furniture or devices do you use on a regular basis? Please select all that apply.</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">120</td><td style="text-align: left; border: 1px solid #555;">Exercise</td><td style="text-align: left; border: 1px solid #555;">"In a typical week, how many times do you exercise?"</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">121</td><td style="text-align: left; border: 1px solid #555;">Gender</td><td style="text-align: left; border: 1px solid #555;">"Which of the following do you currently identify as? Please select all that apply. If you prefer not to answer, you may leave this question blank."</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">122</td><td style="text-align: left; border: 1px solid #555;">SexualOrientation</td><td style="text-align: left; border: 1px solid #555;">"Which of the following do you currently identify as? Please select all that apply. If you prefer not to answer, you may leave this question blank."</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">123</td><td style="text-align: left; border: 1px solid #555;">EducationParents</td><td style="text-align: left; border: 1px solid #555;">"What is the highest level of education received by either of your parents? If you prefer not to answer, you may leave this question blank."</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">124</td><td style="text-align: left; border: 1px solid #555;">RaceEthnicity</td><td style="text-align: left; border: 1px solid #555;">"Which of the following do you identify as? Please check all that apply. If you prefer not to answer, you may leave this question blank."</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">125</td><td style="text-align: left; border: 1px solid #555;">Age</td><td style="text-align: left; border: 1px solid #555;">"What is your age? If you prefer not to answer, you may leave this question blank."</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">126</td><td style="text-align: left; border: 1px solid #555;">Dependents</td><td style="text-align: left; border: 1px solid #555;">"Do you have any children or other dependents that you care for? If you prefer not to answer, you may leave this question blank."</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">127</td><td style="text-align: left; border: 1px solid #555;">MilitaryUS</td><td style="text-align: left; border: 1px solid #555;">Are you currently serving or have you ever served in the U.S. Military?</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">128</td><td style="text-align: left; border: 1px solid #555;">SurveyTooLong</td><td style="text-align: left; border: 1px solid #555;">How do you feel about the length of the survey that you just completed?</td></tr>
<tr><td style="text-align: left; border: 1px solid #555;">129</td><td style="text-align: left; border: 1px solid #555;">SurveyEasy</td><td style="text-align: left; border: 1px solid #555;">How easy or difficult was this survey to complete?</td></tr>
</table>

<br>

Aunque los datos son insuficientes para alcanzar los objetivos de minería de datos planteados, es un buen punto para iniciar (particularmente para fines de este curso).

### <span style="color:#313f9e; font-weight: bold;">Exploración de los datos:</span>
La forma más inmediata de analizar los datos, ya cargados en un objeto Dataframe, es a través del método <code>describe()</code>:

In [4]:
pd.set_option('display.max_columns', 130)
pd.set_option('max_colwidth', 80)

display(df.describe())

Respondent    AssessJob1    AssessJob2    AssessJob3    AssessJob4  \
count   98855.000000  66985.000000  66985.000000  66985.000000  66985.000000   
mean    50822.971635      6.397089      6.673524      5.906875      4.065791   
std     29321.650410      2.788428      2.531202      2.642734      2.541196   
min         1.000000      1.000000      1.000000      1.000000      1.000000   
25%     25443.500000      4.000000      5.000000      4.000000      2.000000   
50%     50823.000000      7.000000      7.000000      6.000000      4.000000   
75%     76219.500000      9.000000      9.000000      8.000000      6.000000   
max    101592.000000     10.000000     10.000000     10.000000     10.000000   

         AssessJob5    AssessJob6    AssessJob7    AssessJob8    AssessJob9  \
count  66985.000000  66985.000000  66985.000000  66985.000000  66985.000000   
mean       3.953243      4.407196      5.673181      4.225200      7.640009   
std        2.520499      2.502069      2.923998      2.507411      2.407457   
min        1.000000      1.000000      1.000000      1.000000      1.000000   
25%        2.000000      2.000000      3.000000      2.000000      6.000000   
50%        3.000000      4.000000      6.000000      4.000000      8.000000   
75%        6.000000      6.000000      8.000000      6.000000     10.000000   
max       10.000000     10.000000     10.000000     10.000000     10.000000   

        AssessJob10  AssessBenefits1  AssessBenefits2  AssessBenefits3  \
count  66985.000000     64918.000000     64918.000000     64918.000000   
mean       6.057804         1.884177         6.080609         4.450553   
std        2.663405         1.880973         3.080841         2.808365   
min        1.000000         1.000000         1.000000         1.000000   
25%        4.000000         1.000000         3.000000         2.000000   
50%        6.000000         1.000000         6.000000         4.000000   
75%        8.000000         2.000000         9.000000         6.000000   
max       10.000000        11.000000        11.000000        11.000000   

       AssessBenefits4  AssessBenefits5  AssessBenefits6  AssessBenefits7  \
count     64918.000000     64918.000000     64918.000000     64918.000000   
mean          7.563218         7.068101         5.765581         6.948196   
std           2.830099         2.638513         2.851319         2.746491   
min           1.000000         1.000000         1.000000         1.000000   
25%           5.000000         5.000000         3.000000         5.000000   
50%           8.000000         7.000000         5.000000         7.000000   
75%          10.000000         9.000000         8.000000         9.000000   
max          11.000000        11.000000        11.000000        11.000000   

       AssessBenefits8  AssessBenefits9  AssessBenefits10  AssessBenefits11  \
count     64918.000000     64918.000000      64918.000000      64917.000000   
mean          5.615053         7.920746          6.865061          5.838625   
std           2.782918         2.765758          2.687617          2.706479   
min           1.000000         1.000000          1.000000          1.000000   
25%           3.000000         6.000000          5.000000          4.000000   
50%           5.000000         9.000000          7.000000          6.000000   
75%           8.000000        10.000000          9.000000          8.000000   
max          11.000000        11.000000         11.000000         11.000000   

       JobContactPriorities1  JobContactPriorities2  JobContactPriorities3  \
count           48706.000000           48706.000000           48706.000000   
mean                3.035396               1.560588               3.849998   
std                 1.326079               0.906463               1.315095   
min                 1.000000               1.000000               1.000000   
25%                 2.000000               1.000000               3.000000   
50%                 3.000000        

<ul>
<li>Como puede observarse, el método <code>describe()</code> despliega, por default, los análisis sólo para los datos numéricos.</li>
<li>Se incluye el análisis de <code>Respondent</code>, lo cual no arroja información útil al ser el ID del usuario.</li>
<li>Observemos que, mientras que hay 98855 registros en la tabla, la variable <code>count</code> en las otras columnas numéricas no supera 2/3 partes, lo cual indica que al menos 1/3 parte de los encuestados no respondió estas preguntas.</li>
<li>Se pueden obtener algunas conclusiones preliminares analizando estos datos, por ejemplo, la respuesta mejor rankeada a la pregunta "Imagine that you are assessing a potential job opportunity. Please rank the following aspects of the job opportunity in order of importance..." fue la número 9: "The diversity of the company or organization". Aunque este resultado, por ejemplo, ya es un indicador interesante para los reclutadores, su alcance es muy vago.</li>
</ul>
Para analizar las respuestas a las demás preguntas, agregamos el atributo <code>include</code>:

In [5]:
print(df.describe(include=[np.object]))

        Hobby OpenSource        Country Student          Employment  \
count   98855      98855          98443   94901               95321   
unique      2          2            183       3                   6   
top       Yes         No  United States      No  Employed full-time   
freq    79897      55769          20309   70399               70495   

                                 FormalEducation  \
count                                      94703   
unique                                         9   
top     Bachelor’s degree (BA, BS, B.Eng., etc.)   
freq                                       43659   

                                                         UndergradMajor  \
count                                                             79036   
unique                                                               12   
top     Computer science, computer engineering, or software engineering   
freq                                                              50336   

       

Aquí aparecen ya datos que son interesantes: destaca por ejemplo, la gran proporcion de encuestados que trabajan de tiempo completo, pero que programan como "hobby"; a la pregunta correspondiente a la columna <code>LanguageWorkedWith</code> (que se autoexplica) sobresale que hay 26678 respuestas diferentes (<code>unique</code>), lo cual es consecuencia de que las respuestas pueden ser múltiples (<code>C#;JavaScript;SQL;HTML;CSS</code>), mientras que para la pregunta <code>LanguageDesireNextYear</code> el lenguaje más deseado es Python, de entre un total de 28657 respuestas diferentes y con una frecuencia de 908 (el 1.2% de quienes respondieron la pregunta y el 0.9% del total de encuestados). 

Para un análisis más descriptivo, particularmente para el caso de las variables categóricas, analicemos las distribución de las respuestas por pregunta.

In [6]:
# Instalar plotly
import plotly as py
import plotly.graph_objs as go
from IPython.display import display, HTML
from collections import Counter

py.offline.init_notebook_mode(connected=True)

In [7]:
# Contabiliza etiquetas
def get_counters(col_name, label):
    full_list = ";".join(col_name)
    each_word = full_list.split(";")
    each_word = Counter(each_word).most_common()
    return pd.DataFrame(each_word, columns = [label, "Participantes"])

# Calcular porcentajes
def percent (row, col):
    count = df[col].count()
    return 100 * row[1] / count

<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
2. Hobby:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Do you code as a hobby?
</div>
</div>

In [8]:
print(df['Hobby'].describe())

data = get_counters(df['Hobby'].dropna(), "Codifica por hobby")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'Hobby'),axis=1)

display(HTML(data.to_html()))

count     98855
unique        2
top         Yes
freq      79897
Name: Hobby, dtype: object


In [9]:
def get_fig_pie(data, hole = 0, pull = 0):
    labels = [w if len(w)<=30 else w[0:30]+"..." for w in data.iloc[:,0]]
    dg = [
        go.Pie(labels=labels, 
               values=data.iloc[0:,1],
               hole = hole,
               pull = pull,
               hoverinfo = "label+percent",
              )
    ]
    layout = go.Layout(
        autosize=False,
        width=750,
        height=500,
    )
    return go.Figure(data=dg, layout=layout)

fig = get_fig_pie(data)
py.offline.iplot(fig)

<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
3. OpenSource:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Do you contribute to open source projects?
</div>
</div>

In [10]:
print(df['OpenSource'].describe())

data = get_counters(df['OpenSource'].dropna(), "Proyectos Open Source")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'OpenSource'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data, hole = 0.4)
py.offline.iplot(fig)

count     98855
unique        2
top          No
freq      55769
Name: OpenSource, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
4. Country:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
In which country do you currently reside?
</div>
</div>

In [11]:
print(df['Country'].describe())

data = get_counters(df['Country'].dropna(), "País")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'Country'),axis=1)
display(HTML(data.to_html()))

count             98443
unique              183
top       United States
freq              20309
Name: Country, dtype: object


In [12]:
data_g = [ dict(
        type = 'choropleth',
        locations = data['País'],
        locationmode = "country names",
        z = data['Participantes'],
        text = data['País'],
        autocolorscale = False,
        reversescale = True,
        marker = dict(
            line = dict (
                color = 'rgb(180,180,180)',
                width = 0.5
            ) ),
        colorbar = dict(
            autotick = True,
            title = 'Cantidad'),
      ) ]

layout = dict(
    title = 'Participantes por país',
    geo = dict(
        showframe = True,
        showcoastlines = True,
        projection = dict(
            type = 'Mercator'
        )
    )
)

fig = dict( data=data_g, layout=layout )

py.offline.iplot( fig, validate=False )

<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
5. Student:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Are you currently enrolled in a formal, degree-granting college or university program?
</div>
</div>

In [13]:
print(df['Student'].describe())

data = get_counters(df['Student'].dropna(), "Es estudiante")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'Student'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data, hole = 0.2, pull = 0.1)
py.offline.iplot(fig)

count     94901
unique        3
top          No
freq      70399
Name: Student, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
6. Employment:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Which of the following best describes your current employment status?
</div>
</div>

In [14]:
print(df['Employment'].describe())

data = get_counters(df['Employment'].dropna(), "Está empleado")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'Employment'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data, hole = 0.2, pull = 0.1)
py.offline.iplot(fig)

count                  95321
unique                     6
top       Employed full-time
freq                   70495
Name: Employment, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
7. FormalEducation:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Which of the following best describes the highest level of formal education that you’ve completed?
</div>
</div>

In [15]:
print(df['FormalEducation'].describe())

data = get_counters(df['FormalEducation'].dropna(), "Educación formal")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'FormalEducation'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data, pull = 0.1)
py.offline.iplot(fig)

count                                        94703
unique                                           9
top       Bachelor’s degree (BA, BS, B.Eng., etc.)
freq                                         43659
Name: FormalEducation, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
8. UndergradMajor:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
You previously indicated that you went to a college or university. Which of the following best describes your main field of study (aka 'major')
</div>
</div>

In [16]:
print(df['UndergradMajor'].describe())

data = get_counters(df['UndergradMajor'].dropna(), "Área de especialidad")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'UndergradMajor'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data)
py.offline.iplot(fig)

count                                                               79036
unique                                                                 12
top       Computer science, computer engineering, or software engineering
freq                                                                50336
Name: UndergradMajor, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
9. CompanySize:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Approximately how many people are employed by the company or organization you work for?
</div>
</div>

In [17]:
print(df['CompanySize'].describe())

data = get_counters(df['CompanySize'].dropna(), "Tamaño de la empresa")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'CompanySize'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data)
py.offline.iplot(fig)

count                  71531
unique                     8
top       20 to 99 employees
freq                   16996
Name: CompanySize, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
10. DevType:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Which of the following describe you? Please select all that apply.
</div>
</div>

In [18]:
print(df['DevType'].describe())

data = get_counters(df['DevType'].dropna(), "Tipo de desarrollador")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'DevType'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data, hole = 0.2, pull = 0.1)
py.offline.iplot(fig)

count                  92098
unique                  9568
top       Back-end developer
freq                    6417
Name: DevType, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
11. YearsCoding:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Including any education, for how many years have you been coding?
</div>
</div>

In [19]:
def get_fig_bar(data):
    dg = [go.Bar(
        x=data.iloc[:, 0],
        y=data.iloc[:, 1],
    )]
    
    layout = go.Layout(
        xaxis=dict(
            title=list(data)[0],
            dtick=1.0,
            tickangle=10
        ),
        yaxis=dict(
            title=list(data)[1]
        )
    )
    return go.Figure(data=dg, layout=layout)

In [20]:
print(df['YearsCoding'].describe())

data = get_counters(df['YearsCoding'].dropna(), "Años codificando")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'YearsCoding'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_bar(data)
py.offline.iplot(fig)

count         93835
unique           11
top       3-5 years
freq          23313
Name: YearsCoding, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
12. YearsCodingProf:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
For how many years have you coded professionally (as a part of your work)?
</div>
</div>

In [21]:
print(df['YearsCodingProf'].describe())

data = get_counters(df['YearsCodingProf'].dropna(), "Años codificando profesionalmente")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'YearsCodingProf'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_bar(data)
py.offline.iplot(fig)

count         77903
unique           11
top       0-2 years
freq          23421
Name: YearsCodingProf, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
13. JobSatisfaction:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
How satisfied are you with your current job? If you work more than one job, please answer regarding the one you spend the most hours on.
</div>
</div>

In [22]:
print(df['JobSatisfaction'].describe())

data = get_counters(df['JobSatisfaction'].dropna(), "Satisfacción en el empleo")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'JobSatisfaction'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_bar(data) 
py.offline.iplot(fig)

count                    69276
unique                       7
top       Moderately satisfied
freq                     26005
Name: JobSatisfaction, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
14. CareerSatisfaction:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Overall, how satisfied are you with your career thus far?
</div>
</div>

In [23]:
print(df['CareerSatisfaction'].describe())

data = get_counters(df['CareerSatisfaction'].dropna(), "Satisfacción profesional")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'CareerSatisfaction'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_bar(data) 
py.offline.iplot(fig)

count                    76504
unique                       7
top       Moderately satisfied
freq                     27926
Name: CareerSatisfaction, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
15. HopeFiveYears:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Which of the following best describes what you hope to be doing in five years?
</div>
</div>

In [24]:
print(df['HopeFiveYears'].describe())

data = get_counters(df['HopeFiveYears'].dropna(), "Esperanza a 5 años")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'HopeFiveYears'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data, hole = 0.2, pull = 0.1)
py.offline.iplot(fig)

count                                                                               75718
unique                                                                                  7
top       Working in a different or more specialized technical role than the one I'm i...
freq                                                                                25643
Name: HopeFiveYears, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
16. JobSearchStatus:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Which of the following best describes your current job-seeking status?
</div>
</div>

In [25]:
print(df['JobSearchStatus'].describe())

data = get_counters(df['JobSearchStatus'].dropna(), "Búsqueda de empleo")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'JobSearchStatus'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data, hole = 0.2, pull = 0.1)
py.offline.iplot(fig)

count                                                            79488
unique                                                               3
top       I’m not actively looking, but I am open to new opportunities
freq                                                             47556
Name: JobSearchStatus, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
17. LastNewJob:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
When was the last time that you took a job with a new employer?
</div>
</div>

In [26]:
print(df['LastNewJob'].describe())

data = get_counters(df['LastNewJob'].dropna(), "Tiempo en el nuevo empleo")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'LastNewJob'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data, hole = 0.2, pull = 0.1)
py.offline.iplot(fig)

count                    78889
unique                       5
top       Less than a year ago
freq                     27321
Name: LastNewJob, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
18. AssessJob1:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Imagine that you are assessing a potential job opportunity. Please rank the following aspects of the job opportunity in order of importance (by dragging the choices up and down), where 1 is the most important and 10 is the least important. <b>The industry that I'd be working in</b>.
</div>
</div>

In [27]:
def get_counters_numeric(col, label):
    series = col.value_counts()
    return pd.DataFrame({label: list(series.keys()), "Participantes": list(series)}, 
                    columns = [label, "Participantes"])

In [28]:
print(df['AssessJob1'].describe())

data = get_counters_numeric(df['AssessJob1'].dropna(), "Importancia de la Industria")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'AssessJob1'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_bar(data)
py.offline.iplot(fig)

count    66985.000000
mean         6.397089
std          2.788428
min          1.000000
25%          4.000000
50%          7.000000
75%          9.000000
max         10.000000
Name: AssessJob1, dtype: float64


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
19. AssessJob2:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Imagine that you are assessing a potential job opportunity. Please rank the following aspects of the job opportunity in order of importance (by dragging the choices up and down), where 1 is the most important and 10 is the least important. <b>The financial performance or funding status of the company or organization</b>.
</div>
</div>

In [29]:
print(df['AssessJob2'].describe())

data = get_counters_numeric(df['AssessJob2'].dropna(), "Finanzas de la empresa")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'AssessJob2'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_bar(data)
py.offline.iplot(fig)

count    66985.000000
mean         6.673524
std          2.531202
min          1.000000
25%          5.000000
50%          7.000000
75%          9.000000
max         10.000000
Name: AssessJob2, dtype: float64


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
20. AssessJob3:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Imagine that you are assessing a potential job opportunity. Please rank the following aspects of the job opportunity in order of importance (by dragging the choices up and down), where 1 is the most important and 10 is the least important. <b> The specific department or team I'd be working on</b>.
</div>
</div>

In [30]:
print(df['AssessJob3'].describe())

data = get_counters_numeric(df['AssessJob3'].dropna(), "Equipo para el que trabajo")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'AssessJob3'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_bar(data)
py.offline.iplot(fig)

count    66985.000000
mean         5.906875
std          2.642734
min          1.000000
25%          4.000000
50%          6.000000
75%          8.000000
max         10.000000
Name: AssessJob3, dtype: float64


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
21. AssessJob4:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Imagine that you are assessing a potential job opportunity. Please rank the following aspects of the job opportunity in order of importance (by dragging the choices up and down), where 1 is the most important and 10 is the least important. <b>The languages, frameworks, and other technologies I'd be working with</b>.
</div>
</div>

In [31]:
print(df['AssessJob5'].describe())

data = get_counters_numeric(df['AssessJob5'].dropna(), "Tecnologías utilizadas")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'AssessJob5'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_bar(data)
py.offline.iplot(fig)

count    66985.000000
mean         3.953243
std          2.520499
min          1.000000
25%          2.000000
50%          3.000000
75%          6.000000
max         10.000000
Name: AssessJob5, dtype: float64


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
22. AssessJob5:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Imagine that you are assessing a potential job opportunity. Please rank the following aspects of the job opportunity in order of importance (by dragging the choices up and down), where 1 is the most important and 10 is the least important. <b>The compensation and benefits offered</b>.
</div>
</div>

In [32]:
print(df['AssessJob5'].describe())

data = get_counters_numeric(df['AssessJob5'].dropna(), "Compensaciones")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'AssessJob5'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_bar(data)
py.offline.iplot(fig)

count    66985.000000
mean         3.953243
std          2.520499
min          1.000000
25%          2.000000
50%          3.000000
75%          6.000000
max         10.000000
Name: AssessJob5, dtype: float64


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
23. AssessJob6:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Imagine that you are assessing a potential job opportunity. Please rank the following aspects of the job opportunity in order of importance (by dragging the choices up and down), where 1 is the most important and 10 is the least important. <b>The office environment or company culture</b>.
</div>
</div>

In [33]:
print(df['AssessJob6'].describe())

data = get_counters_numeric(df['AssessJob6'].dropna(), "Cultura organizacional")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'AssessJob6'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_bar(data)
py.offline.iplot(fig)

count    66985.000000
mean         4.407196
std          2.502069
min          1.000000
25%          2.000000
50%          4.000000
75%          6.000000
max         10.000000
Name: AssessJob6, dtype: float64


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
24. AssessJob7:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Imagine that you are assessing a potential job opportunity. Please rank the following aspects of the job opportunity in order of importance (by dragging the choices up and down), where 1 is the most important and 10 is the least important. <b>The opportunity to work from home/remotely</b>.
</div>
</div>

In [34]:
print(df['AssessJob7'].describe())

data = get_counters_numeric(df['AssessJob7'].dropna(), "Trabajo desde casa")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'AssessJob7'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_bar(data)
py.offline.iplot(fig,)

count    66985.000000
mean         5.673181
std          2.923998
min          1.000000
25%          3.000000
50%          6.000000
75%          8.000000
max         10.000000
Name: AssessJob7, dtype: float64


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
25. AssessJob8:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Imagine that you are assessing a potential job opportunity. Please rank the following aspects of the job opportunity in order of importance (by dragging the choices up and down), where 1 is the most important and 10 is the least important. <b>Opportunities for professional development</b>.
</div>
</div>

In [35]:
print(df['AssessJob8'].describe())

data = get_counters_numeric(df['AssessJob8'].dropna(), "Oportunidades de desarrollo")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'AssessJob8'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_bar(data)
py.offline.iplot(fig)

count    66985.000000
mean         4.225200
std          2.507411
min          1.000000
25%          2.000000
50%          4.000000
75%          6.000000
max         10.000000
Name: AssessJob8, dtype: float64


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
26. AssessJob9:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Imagine that you are assessing a potential job opportunity. Please rank the following aspects of the job opportunity in order of importance (by dragging the choices up and down), where 1 is the most important and 10 is the least important. <b>The diversity of the company or organization</b>.
</div>
</div>

In [36]:
print(df['AssessJob9'].describe())

data = get_counters_numeric(df['AssessJob9'].dropna(), "Diversidad de la empresa")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'AssessJob9'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_bar(data)
py.offline.iplot(fig)

count    66985.000000
mean         7.640009
std          2.407457
min          1.000000
25%          6.000000
50%          8.000000
75%         10.000000
max         10.000000
Name: AssessJob9, dtype: float64


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
27. AssessJob10:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Imagine that you are assessing a potential job opportunity. Please rank the following aspects of the job opportunity in order of importance (by dragging the choices up and down), where 1 is the most important and 10 is the least important. <b>How widely used or impactful the product or service I'd be working on is</b>.
</div>
</div>

In [37]:
print(df['AssessJob10'].describe())

data = get_counters_numeric(df['AssessJob10'].dropna(), "Importancia de mi trabajo")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'AssessJob10'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_bar(data)
py.offline.iplot(fig)

count    66985.000000
mean         6.057804
std          2.663405
min          1.000000
25%          4.000000
50%          6.000000
75%          8.000000
max         10.000000
Name: AssessJob10, dtype: float64


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
28-38. <br>AssessBenefits1 - <br>AssessBenefits11:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Now, imagine you are assessing a job's benefits package. Please rank the following aspects of a job's benefits package from most to least important to you (by dragging the choices up and down), where 1 is most important and 11 is least important.
<b>
<ol>
<li>Salary and/or bonuses</li>
<li>Stock options or shares</li>
<li>Health insurance</li>
<li>Parental leave</li>
<li>Fitness or wellness benefit (ex. gym membership, nutritionist)</li>
<li>Retirement or pension savings matching</li>
<li>Company-provided meals or snacks</li>
<li>Computer/office equipment allowance</li>
<li>Childcare benefit</li>
<li>Transportation benefit (ex. company-provided transportation, public transit allowance)</li>
<li>Conference or education budget</li>
</ol>
</b>
</div>
</div>

In [38]:
columns = list(df.columns.values[27:38])
labels = ['Compensaciones', 'Acciones de la empresa', 'Seguridad médica', 'Licencia parental',
         'Beneficios de aptitud', 'Pensión', 'Botanas', 'Tolerancia de equipo', 
         'Cuidado infantil', 'Transporte', 'Capacitación']

counter = 28
for col, label in zip(columns, labels):
    display(HTML('<hr style="border-width: 3px;">'))
    display(HTML('<span style="color:blue; font-weight: bold;">' + str(counter) + ". " + 
                 col + ": " +'</span>' + '<span style="font-weight: bold;">'  + 
                 label +'</span>'))
    print(df[col].describe())
    data = get_counters_numeric(df[col].dropna(), label)
    data['Porcentaje'] = data.apply (lambda row: percent (row, col),axis=1)
    display(HTML(data.to_html()))
    fig = get_fig_bar(data)
    py.offline.iplot(fig)
    counter += 1
    print()

count    64918.000000
mean         1.884177
std          1.880973
min          1.000000
25%          1.000000
50%          1.000000
75%          2.000000
max         11.000000
Name: AssessBenefits1, dtype: float64


count    64918.000000
mean         6.080609
std          3.080841
min          1.000000
25%          3.000000
50%          6.000000
75%          9.000000
max         11.000000
Name: AssessBenefits2, dtype: float64


count    64918.000000
mean         4.450553
std          2.808365
min          1.000000
25%          2.000000
50%          4.000000
75%          6.000000
max         11.000000
Name: AssessBenefits3, dtype: float64


count    64918.000000
mean         7.563218
std          2.830099
min          1.000000
25%          5.000000
50%          8.000000
75%         10.000000
max         11.000000
Name: AssessBenefits4, dtype: float64


count    64918.000000
mean         7.068101
std          2.638513
min          1.000000
25%          5.000000
50%          7.000000
75%          9.000000
max         11.000000
Name: AssessBenefits5, dtype: float64


count    64918.000000
mean         5.765581
std          2.851319
min          1.000000
25%          3.000000
50%          5.000000
75%          8.000000
max         11.000000
Name: AssessBenefits6, dtype: float64


count    64918.000000
mean         6.948196
std          2.746491
min          1.000000
25%          5.000000
50%          7.000000
75%          9.000000
max         11.000000
Name: AssessBenefits7, dtype: float64


count    64918.000000
mean         5.615053
std          2.782918
min          1.000000
25%          3.000000
50%          5.000000
75%          8.000000
max         11.000000
Name: AssessBenefits8, dtype: float64


count    64918.000000
mean         7.920746
std          2.765758
min          1.000000
25%          6.000000
50%          9.000000
75%         10.000000
max         11.000000
Name: AssessBenefits9, dtype: float64


count    64918.000000
mean         6.865061
std          2.687617
min          1.000000
25%          5.000000
50%          7.000000
75%          9.000000
max         11.000000
Name: AssessBenefits10, dtype: float64


count    64917.000000
mean         5.838625
std          2.706479
min          1.000000
25%          4.000000
50%          6.000000
75%          8.000000
max         11.000000
Name: AssessBenefits11, dtype: float64


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:25%; float:left; padding-right:5px; color:blue; font-weight: bold;">
39-43. <br>JobContactPriorities1 - <br>JobContactPriorities5:
</div>

<div style="margin-left: 25%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Imagine that a company wanted to contact you about a job that is a good fit for you. Please rank your preference in how you are contacted (by dragging the choices up and down), where 1 is the most preferred and 5 is the least preferred.
<b>
<ol>
<li>Telephone call</li>
<li>Email to my private address</li>
<li>Email to my work address</li>
<li>Message on a job site</li>
<li>Message on a social media site</li>
</ol>
</b>
</div>
</div>

Para casos como el presente, es conveniente visualizar los resultados del conjunto de variables en una sola gráfica. 

In [39]:
def get_fig_bar_mult(columns, labels, x_data, angle_likert = 0):
    colors = random_colors(len(columns))

    traces = []
    for i in range(0, len(x_data[0])):
        for xd, yd in zip(x_data, labels):
            traces.append(go.Bar(
                x=[xd[i]],
                y=[yd],
                orientation='h',
                marker=dict(
                    color=colors[i],
                    line=dict(
                            color='rgb(248, 248, 249)',
                            width=1)
                )
            ))

    layout = go.Layout(
        xaxis=dict(
            showgrid=False,
            showline=False,
            showticklabels=False,
            zeroline=False,
            domain=[0.15, 1]
        ),
        yaxis=dict(
            showgrid=False,
            showline=False,
            showticklabels=False,
            zeroline=False,
        ),
        barmode='stack',
        paper_bgcolor='rgb(248, 248, 255)',
        plot_bgcolor='rgb(248, 248, 255)',
        margin=dict(
            l=120,
            r=10,
            t=140,
            b=80
        ),
        hovermode='closest',
        showlegend=False,
    )

    annotations = []
    for yd, xd in zip(labels, x_data):
        # labeling the y-axis
        annotations.append(dict(xref='paper', yref='y',
                                x=0.14, y=yd,
                                xanchor='right',
                                text=str(yd),
                                font=dict(family='Arial', size=14,
                                          color='rgb(67, 67, 67)'),
                                showarrow=False, align='right',
                               )
                          )
        # labeling the first Likert scale (on the top)
        if yd == labels[-1]:
            annotations.append(dict(xref='x', yref='paper',
                                    x=xd[0] / 2, y=1.1,
                                    text=top_labels[0],
                                    font=dict(family='Arial', size=14,
                                              color='rgb(67, 67, 67)'),
                                    showarrow=False,
                                    textangle = angle_likert
                                   )
                              )
        space = xd[0]
        for i in range(1, len(xd)):
                # labeling the Likert scale
                if yd == labels[-1]:
                    annotations.append(dict(xref='x', yref='paper',
                                            x=space + (xd[i]/2), y=1.1,
                                            text=top_labels[i],
                                            font=dict(family='Arial', size=14,
                                                      color='rgb(67, 67, 67)'),
                                            showarrow=False,
                                            textangle = angle_likert
                                           )
                                      )
                space += xd[i]
    layout['annotations'] = annotations

    return go.Figure(data=traces, layout=layout)

In [40]:
import random

def random_colors(number_of_colors):
    color = ["#"+''.join([random.choice('0123456789ABCD') for j in range(6)])
                 for i in range(number_of_colors)]
    return color

In [41]:
columns = list(df.columns.values[38:43])
labels = ['Llamada telefónica', 'Correo privado', 'Correo de trabajo', 
          'Mensaje al sitio de trabajo','Mensaje en redes sociales']

top_labels = []
x_data = []
counter = 39
for col, label in zip(columns, labels):
    display(HTML('<hr style="border-width: 3px;">'))
    display(HTML('<span style="color:blue; font-weight: bold;">' + str(counter) + ". " + 
                 col + ": " +'</span>' + '<span style="font-weight: bold;">'  + 
                 label +'</span>'))
    print(df[col].describe())
    d = get_counters_numeric(df[col].dropna(), label)
    d['Porcentaje'] = d.apply (lambda row: percent (row, col), axis=1)
    display(HTML(d.to_html()))
    
    dsorted = d.sort_values(d.columns[0])
    if len(top_labels) == 0:
        top_labels = list(dsorted.iloc[:,0])
    x_data.append(list(dsorted.iloc[:,1]))
    counter += 1

fig = get_fig_bar_mult(columns, labels, x_data)
    
py.offline.iplot(fig)

count    48706.000000
mean         3.035396
std          1.326079
min          1.000000
25%          2.000000
50%          3.000000
75%          4.000000
max          5.000000
Name: JobContactPriorities1, dtype: float64


count    48706.000000
mean         1.560588
std          0.906463
min          1.000000
25%          1.000000
50%          1.000000
75%          2.000000
max          5.000000
Name: JobContactPriorities2, dtype: float64


count    48706.000000
mean         3.849998
std          1.315095
min          1.000000
25%          3.000000
50%          4.000000
75%          5.000000
max          5.000000
Name: JobContactPriorities3, dtype: float64


count    48706.000000
mean         3.005112
std          1.160622
min          1.000000
25%          2.000000
50%          3.000000
75%          4.000000
max          5.000000
Name: JobContactPriorities4, dtype: float64


count    48706.000000
mean         3.548906
std          1.116461
min          1.000000
25%          3.000000
50%          4.000000
75%          4.000000
max          5.000000
Name: JobContactPriorities5, dtype: float64


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:25%; float:left; padding-right:5px; color:blue; font-weight: bold;">
44-50. <br>JobEmailPriorities1 - <br>JobEmailPriorities7:
</div>

<div style="margin-left: 25%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Imagine that same company decided to contact you through email. Please rank the following items by how important it is to include them in the message (by dragging the choices up and down), where 1 is the most important and 7 is the least important. 
<b>
<ol>
<li>Details on the company I'd be working for</li>
<li>Details on the specific department I'd be working for or product I'd be working on</li>
<li>Specifics of why they think I'd be a good fit for the role (ex. my prior work history, projects on GitHub)</li>
<li>Details of which technologies I'd be working with</li>
<li>An estimate of the compensation range</li>
<li>Information on the company's hiring process</li>
<li>Details on the company's product development process</li>
</ol>
</b>
</div>
</div>

In [42]:
columns = list(df.columns.values[43:50])
labels = ['Detalles de la empresa', 'Detalles del departamento', 'Razones de contratación', 
          'Tecnologías a usar', 'Rango de compensaciones','Proceso de contratación', 
          'Proceso de desarrollo']

top_labels = []
x_data = []
counter = 44
for col, label in zip(columns, labels):
    display(HTML('<hr style="border-width: 3px;">'))
    display(HTML('<span style="color:blue; font-weight: bold;">' + str(counter) + ". " + 
                 col + ": " +'</span>' + '<span style="font-weight: bold;">'  + 
                 label +'</span>'))
    print(df[col].describe())
    d = get_counters_numeric(df[col].dropna(), label)
    d['Porcentaje'] = d.apply (lambda row: percent (row, col), axis=1)
    display(HTML(d.to_html()))
    
    dsorted = d.sort_values(d.columns[0])
    if len(top_labels) == 0:
        top_labels = list(dsorted.iloc[:,0])
    x_data.append(list(dsorted.iloc[:,1]))
    counter += 1

fig = get_fig_bar_mult(columns, labels, x_data)
    
py.offline.iplot(fig)

count    46213.000000
mean         3.709541
std          2.071172
min          1.000000
25%          2.000000
50%          4.000000
75%          6.000000
max          7.000000
Name: JobEmailPriorities1, dtype: float64


count    46213.000000
mean         4.224309
std          1.842500
min          1.000000
25%          3.000000
50%          4.000000
75%          6.000000
max          7.000000
Name: JobEmailPriorities2, dtype: float64


count    46213.000000
mean         3.796572
std          2.082178
min          1.000000
25%          2.000000
50%          4.000000
75%          6.000000
max          7.000000
Name: JobEmailPriorities3, dtype: float64


count    46213.000000
mean         3.015602
std          1.651321
min          1.000000
25%          2.000000
50%          3.000000
75%          4.000000
max          7.000000
Name: JobEmailPriorities4, dtype: float64


count    46213.000000
mean         3.443338
std          1.983163
min          1.000000
25%          2.000000
50%          3.000000
75%          5.000000
max          7.000000
Name: JobEmailPriorities5, dtype: float64


count    46213.00000
mean         4.97425
std          1.86063
min          1.00000
25%          4.00000
50%          5.00000
75%          7.00000
max          7.00000
Name: JobEmailPriorities6, dtype: float64


count    46213.000000
mean         4.836388
std          1.659844
min          1.000000
25%          4.000000
50%          5.000000
75%          6.000000
max          7.000000
Name: JobEmailPriorities7, dtype: float64


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
51. UpdateCV:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Think back to the last time you updated your resumé, CV, or an online profile on a job site. What is the main reason that you did so?
</div>
</div>

In [43]:
print(df['UpdateCV'].describe())

data = get_counters(df['UpdateCV'].dropna(), "Razón de actualización CV")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'UpdateCV'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data, hole = 0.2, pull = 0.1)
py.offline.iplot(fig)

count                                              65539
unique                                                 8
top       My job status or other personal status changed
freq                                               27344
Name: UpdateCV, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
52. Currency:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Which currency do you use day-to-day? If your answer is complicated, please pick the one you're most comfortable estimating in.
</div>
</div>

In [44]:
print(df['Currency'].describe())

data = get_counters(df['Currency'].dropna(), "Divisa")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'Currency'),axis=1)
display(HTML(data.to_html()))

count                62008
unique                  19
top       U.S. dollars ($)
freq                 20601
Name: Currency, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
53. Salary:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
What is your current gross salary (before taxes and deductions), in...? Please enter a whole number in the box below, without any punctuation. If you are paid hourly, please estimate an equivalent weekly, monthly, or yearly salary. If you prefer not to answer, please leave the box empty.
</div>
</div>

In [45]:
print(df['Salary'].describe())

count     50578
unique     3998
top           0
freq       1121
Name: Salary, dtype: object


En el caso de la variable 'Salary', llama la atención que no aparezca como variable numérica. Observamos los 3998 valores diferentes: 

In [46]:
salary_list = df['Salary'].value_counts()
print(salary_list.index.tolist())  

['0', '60000', '100000', '50000', '80000', '120000', '70000', '40000', '30000', '90000', '45000', '75000', '65000', '150000', '55000', '35000', '110000', '3000', '85000', '130000', '2000', '25000', '4000', '10000', '5000', '20000', '1000', '15000', '140000', '125000', '2500', '1500', '105000', '95000', '115000', '42000', '3500', '6000', '32000', '12000', '200000', '48000', '160000', '36000', '8000', '135000', '1200', '72000', '38000', '28000', '180000', '500', '24000', '52000', '18000', '7000', '4500', '800', '33000', '300000', '27000', '68000', '22000', '500000', '2200', '1800', '58000', '26000', '62000', '56000', '37000', '170000', '16000', '78000', '54000', '145000', '43000', '600000', '600', '3200', '34000', '2400', '1000000', '57000', '1400', '1600', '9000', '46000', '14000', '250000', '63000', '2600', '800000', '13000', '400', '44000', '92000', '53000', '82000', '2800', '31000', '700', '1300', '41000', '1200000', '66000', '23000', '47000', '29000', '39000', '1100', '175000', '110

<div style="width:100%; overflow:hidden;">
<div style="width:15%; float:left; padding-right:5px; color:red; font-weight: bold;">
Error:
</div>

<div style="margin-left: 15%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Observamos que esta variable está muy sucia, además de que, al parecer, mezcla diferentes modalidades y monedas de pago, como se desprende de las siguientes variables (y de 52. Currency):
</div>
</div>

<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
54. SalaryType:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Is that salary weekly, monthly, or yearly?
</div>
</div>

In [47]:
print(df['SalaryType'].describe())

data = get_counters(df['SalaryType'].dropna(), "Tipo de salario")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'SalaryType'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data, hole = 0.2, pull = 0.1)
py.offline.iplot(fig)

count       51070
unique          3
top       Monthly
freq        26252
Name: SalaryType, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
55. ConvertedSalary:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Salary converted to annual USD salaries using the exchange rate on 2018-01-18, assuming 12 working months and 50 working weeks.
</div>
</div>

In [48]:
print(df['ConvertedSalary'].describe())

data = get_counters_numeric(df['ConvertedSalary'].dropna(), "Tipo convertido")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'ConvertedSalary'),axis=1)

count    4.770200e+04
mean     9.578086e+04
std      2.023482e+05
min      0.000000e+00
25%      2.384400e+04
50%      5.507500e+04
75%      9.300000e+04
max      2.000000e+06
Name: ConvertedSalary, dtype: float64


<div style="width:100%; overflow:hidden;">
<div style="width:15%; float:left; padding-right:5px; color:orange; font-weight: bold;">
Precaución:
</div>

<div style="margin-left: 15%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
En este caso, podemos preveer que la conversión a dólares sea incorrecta, dado que los datos de donde se calcula (posiblemente) están sucios. 
</div>
</div>

<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
56. CurrencySymbol:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Three digit currency abbreviation.
</div>
</div>

In [49]:
print(df['CurrencySymbol'].describe())

data = get_counters(df['CurrencySymbol'].dropna(), "Símbolo de divisa")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'CurrencySymbol'),axis=1)
display(HTML(data.to_html()))

count     58650
unique      112
top         USD
freq      17330
Name: CurrencySymbol, dtype: object


<div style="width:100%; overflow:hidden;">
<div style="width:15%; float:left; padding-right:5px; color:red; font-weight: bold;">
Error:
</div>

<div style="margin-left: 15%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Observamos que no hay concordancia entre las variables 'Currency' y 'CurrencySymbol'. 
</div>
</div>

<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
57. CommunicationTools:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Which of the following tools do you use to communicate, coordinate, or share knowledge with your coworkers? Please select all that apply.
</div>
</div>

In [50]:
print(df['CommunicationTools'].describe())

data = get_counters(df['CommunicationTools'].dropna(), "Herramienta de comunicación")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'CommunicationTools'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data)
py.offline.iplot(fig)

count                                                                  56970
unique                                                                  1149
top       Office / productivity suite (Microsoft Office, Google Suite, etc.)
freq                                                                    3523
Name: CommunicationTools, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
58. TimeFullyProductive:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Suppose a new developer with four years of experience, including direct experience working with your company's main technical stack, joined your team tomorrow. All other things being equal, how long would you expect it to take before they were fully productive and contributing at a typical level to your main code base?
</div>
</div>

In [51]:
print(df['TimeFullyProductive'].describe())

data = get_counters(df['TimeFullyProductive'].dropna(), "Tiempo para ser 100% productivo")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'TimeFullyProductive'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_bar(data)
py.offline.iplot(fig)

count                   51872
unique                      6
top       One to three months
freq                    23163
Name: TimeFullyProductive, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
59. EducationTypes:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Which of the following types of non-degree education have you used or participated in? Please select all that apply.
</div>
</div>

In [52]:
print(df['EducationTypes'].describe())

data = get_counters(df['EducationTypes'].dropna(), "Opciones de actualización")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'EducationTypes'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data, hole = 0.2, pull = 0.1)
py.offline.iplot(fig)

count                                                                               67960
unique                                                                                494
top       Taught yourself a new language, framework, or tool without taking a formal c...
freq                                                                                 6900
Name: EducationTypes, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
60. SelfTaughtTypes:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
You indicated that you had taught yourself a programming technology without taking a course. What resources did you use to do that? If you’ve done it more than once, please think about the most recent time you’ve done so. Please select all that apply.
</div>
</div>

In [53]:
print(df['SelfTaughtTypes'].describe())

data = get_counters(df['SelfTaughtTypes'].dropna(), "Recursos de autoaprendizaje")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'SelfTaughtTypes'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data, hole = 0.2, pull = 0.1)
py.offline.iplot(fig)

count                                                                               57354
unique                                                                                471
top       The official documentation and/or standards for the technology;Questions & a...
freq                                                                                 3426
Name: SelfTaughtTypes, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
61. TimeAfterBootcamp:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
You indicated previously that you went through a developer training program or bootcamp. How long did it take you to get a full-time job as a developer after graduating?
</div>
</div>

In [54]:
print(df['TimeAfterBootcamp'].describe())

data = get_counters(df['TimeAfterBootcamp'].dropna(), "Tiempo para contratación")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'TimeAfterBootcamp'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data, hole = 0.2, pull = 0.1)
py.offline.iplot(fig)

count                                                                      6652
unique                                                                        8
top       I already had a full-time job as a developer when I began the program
freq                                                                       3025
Name: TimeAfterBootcamp, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
62. HackathonReasons:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
You indicated previously that you had participated in an online coding competition or hackathon. Which of the following best describe your reasons for doing so?
</div>
</div>

In [55]:
print(df['HackathonReasons'].describe())

data = get_counters(df['HackathonReasons'].dropna(), "Participación en hackathons")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'HackathonReasons'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data, hole = 0.2, pull = 0.1)
py.offline.iplot(fig)

count                                                                               25691
unique                                                                                127
top       To improve my general technical skills or programming ability;To improve my ...
freq                                                                                 3160
Name: HackathonReasons, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
63-65. <br>AgreeDisagree1 - AgreeDisagree3:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
To what extent do you agree or disagree with each of the following statements?

<b>
<ol>
<li>I feel a sense of kinship or connection to other developers.</li>
<li>I think of myself as competing with my peers.</li>
<li>I'm not as good at programming as most of my peers.</li>
</ol>
</b>
</div>

<br>
<div style="border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Para variables que corresponden a una misma pregunta con tres variantes, como en este caso, es conveniente comparar lado a lado los resultados. 
</div>
</div>

In [56]:
def get_fig_bar_group(data, labels, option = 'group'): #'group' / 'stack'
    traces = []
    colors = random_colors(len(data))
    for i in range(len(data)):
        traces.append(go.Bar(
            x=data[i].iloc[:,0],
            y=data[i].iloc[:,1],
            name=labels[i],
            marker=dict(
                color=colors[i]
            )
        ))
        
    layout = go.Layout(
        xaxis=dict(tickangle=15),
        barmode=option,
    )
    
    return go.Figure(data=traces, layout=layout)

In [57]:
columns = list(df.columns.values[62:65])
labels = ["Afinidad con otros desarrolladores", "Competidor de otros desarrolladores",
         "Inferior a otros desarrolladores"]

data = []
counter = 63
sorterIndex = {}
for col, label in zip(columns, labels):
    display(HTML('<hr style="border-width: 3px;">'))
    display(HTML('<span style="color:blue; font-weight: bold;">' + str(counter) + ". " + 
                 col + ": " +'</span>' + '<span style="font-weight: bold;">'  + 
                 label +'</span>'))
    print(df[col].describe())

    d = get_counters(df[col].dropna(), label)
    d['Porcentaje'] = d.apply (lambda row: percent (row, col), axis=1)
    display(HTML(d.to_html()))

    if len(sorterIndex) == 0:
        indices = list(d.iloc[:,0])
        sorterIndex = dict(zip(indices, range(len(indices))))
    else:
        # Utilizar el tipo "category" para usarlo como criterio de ordenamiento
        d.iloc[:,0] = d.iloc[:,0].astype("category")
        d.iloc[:,0].cat.set_categories(sorterIndex, inplace=True)
        d = d.sort_values([d.columns[0]])
    counter += 1
        
    data.append(d)
    
fig = get_fig_bar_group(data, labels) 
py.offline.iplot(fig)

count     68217
unique        5
top       Agree
freq      36777
Name: AgreeDisagree1, dtype: object


count     68346
unique        5
top       Agree
freq      18673
Name: AgreeDisagree2, dtype: object


count        68364
unique           5
top       Disagree
freq         23341
Name: AgreeDisagree3, dtype: object


Aunque en este caso los tres reactivos responden una misma pregunta, hay que notar que no todos los encuestados respondieron las tres variantes de la pregunta, de manera que las barras no son congruentes.

<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
66. LanguageWorkedWith:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Which of the following programming, scripting, and markup languages have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you both worked with the language and want to continue to do so, please check both boxes in that row.).
</div>
</div>

In [58]:
print(df['LanguageWorkedWith'].describe())

data = get_counters(df['LanguageWorkedWith'].dropna(), "Lenguaje utilizado")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'LanguageWorkedWith'),axis=1)
display(HTML(data.to_html()))

count                          78334
unique                         26678
top       C#;JavaScript;SQL;HTML;CSS
freq                            1347
Name: LanguageWorkedWith, dtype: object


In [59]:
# Instalar el módulo squarify
import squarify

def get_fig_treemap(data):
    x = 0
    y = 0
    width = 50
    height = 50

    data = data.head(25)
    type_list = data.iloc[:,0]
    values = data.iloc[:,1]

    normed = squarify.normalize_sizes(values, width, height)
    rects = squarify.squarify(normed, x, y, width, height)
    
    colors = random_colors(20)
    shapes = []
    annotations = []
    counter = 0
    color = 0

    for r in rects:
        shapes.append( 
            dict(
                type = 'rect', 
                x0 = r['x'], 
                y0 = r['y'], 
                x1 = r['x']+r['dx'], 
                y1 = r['y']+r['dy'],
                line = dict( width = 1 ),
                fillcolor = colors[color]
            ) 
        )
        annotations.append(
            dict(
                x = r['x']+(r['dx']/2),
                y = r['y']+(r['dy']/2),
                text = "{}".format(type_list[counter]),
                showarrow = False
            )
        )
        counter = counter + 1
        color = color + 1
        if color >= len(colors):
            color = 0

        trace0 = go.Scatter(
            x = [ r['x']+(r['dx']/2) for r in rects ],
            y = [ r['y']+(r['dy']/2) for r in rects ],
            text = [ str(v) for v in values ], 
            mode = 'text',
        )

        layout = dict(
            height=600, 
            width=750,
            xaxis=dict(showgrid=False,zeroline=False),
            yaxis=dict(showgrid=False,zeroline=False),
            shapes=shapes,
            annotations=annotations,
            hovermode='closest',
            font=dict(color="#FFFFFF"),
            margin = go.layout.Margin(
                l=0,
                r=0,
                pad=0
            )
        )

    return dict(data=[trace0], layout=layout)

figure = get_fig_treemap(data)
py.offline.iplot(figure)

<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:25%; float:left; padding-right:5px; color:blue; font-weight: bold;">
67. LanguageDesireNextYear:
</div>

<div style="margin-left: 25%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Which of the following programming, scripting, and markup languages have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you both worked with the language and want to continue to do so, please check both boxes in that row).
</div>
</div>

In [60]:
print(df['LanguageDesireNextYear'].describe())

data = get_counters(df['LanguageDesireNextYear'].dropna(), 
                    "Lenguaje deseado próximo año")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'LanguageDesireNextYear'),axis=1)
display(HTML(data.to_html()))

figure = get_fig_treemap(data)
py.offline.iplot(figure)

count      73244
unique     28657
top       Python
freq         908
Name: LanguageDesireNextYear, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:25%; float:left; padding-right:5px; color:blue; font-weight: bold;">
68. <br>DatabaseWorkedWith:
</div>

<div style="margin-left: 25%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Which of the following database environments have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you both worked with the database and want to continue to do so, please check both boxes in that row).
</div>
<br>
<div style="width:25%; float:left; padding-right:5px; color:blue; font-weight: bold;">
69. <br>DatabaseDesireNextYear:
</div>

<div style="margin-left: 25%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Which of the following database environments have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you both worked with the database and want to continue to do so, please check both boxes in that row.)
</div>
</div>

Variables que corresponden a etapas diferentes de un mismo evento (base de datos utilizada durante el presente año, contra la base de datos deseada para el próximo año, por ejemplo), es conveniente comparar lado a lado los resultados. 

In [61]:
columns = list(df.columns.values[67:69])
labels = ['Base de datos utilizada', "BD deseada próximo año"]

data = []
counter = 68
sorterIndex = {}
for col, label in zip(columns, labels):
    display(HTML('<hr style="border-width: 3px;">'))
    display(HTML('<span style="color:blue; font-weight: bold;">' + str(counter) + ". " + 
                 col + ": " +'</span>' + '<span style="font-weight: bold;">'  + 
                 label +'</span>'))
    print(df[col].describe())

    d = get_counters(df[col].dropna(), label)
    d['Porcentaje'] = d.apply (lambda row: percent (row, col), axis=1)
    display(HTML(d.to_html()))

    if len(sorterIndex) == 0:
        indices = list(d.iloc[:,0])
        sorterIndex = dict(zip(indices, range(len(indices))))
    else:
        # Utilizar el tipo "category" para usarlo como criterio de ordenamiento
        d.iloc[:,0] = d.iloc[:,0].astype("category")
        d.iloc[:,0].cat.set_categories(sorterIndex, inplace=True)
        d = d.sort_values([d.columns[0]])
    counter += 1
        
    data.append(d)
    
fig = get_fig_bar_group(data, labels) 
py.offline.iplot(fig)

count     66270
unique     6877
top       MySQL
freq       5968
Name: DatabaseWorkedWith, dtype: object


count     57498
unique    10028
top       MySQL
freq       2889
Name: DatabaseDesireNextYear, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:25%; float:left; padding-right:5px; color:blue; font-weight: bold;">
70. <br>PlatformWorkedWith:
</div>

<div style="margin-left: 25%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Which of the following platforms have you done extensive development work for over the past year? (If you both developed for the platform and want to continue to do so, please check both boxes in that row).
</div>

<br>
<div style="width:25%; float:left; padding-right:5px; color:blue; font-weight: bold;">
71. <br>PlatformDesireNextYear:
</div>

<div style="margin-left: 25%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Which of the following platforms have you done extensive development work for over the past year? (If you both developed for the platform and want to continue to do so, please check both boxes in that row).

</div>

In [62]:
columns = list(df.columns.values[69:71])
labels = ["Plataforma utilizada", "Pl deseada próx año"]

data = []
counter = 70
sorterIndex = {}
for col, label in zip(columns, labels):
    display(HTML('<hr style="border-width: 3px;">'))
    display(HTML('<span style="color:blue; font-weight: bold;">' + str(counter) + ". " + 
                 col + ": " +'</span>' + '<span style="font-weight: bold;">'  + 
                 label +'</span>'))
    print(df[col].describe())

    d = get_counters(df[col].dropna(), label)
    d['Porcentaje'] = d.apply (lambda row: percent (row, col), axis=1)
    display(HTML(d.to_html()))

    if len(sorterIndex) == 0:
        indices = list(d.iloc[:,0])
        sorterIndex = dict(zip(indices, range(len(indices))))
    else:
        # Utilizar el tipo "category" para usarlo como criterio de ordenamiento
        d.iloc[:,0] = d.iloc[:,0].astype("category")
        d.iloc[:,0].cat.set_categories(sorterIndex, inplace=True)
        d = d.sort_values([d.columns[0]])
    counter += 1
        
    data.append(d)
    
fig = get_fig_bar_group(data, labels) 
py.offline.iplot(fig)

count                         65999
unique                         9320
top       Windows Desktop or Server
freq                           5419
Name: PlatformWorkedWith, dtype: object


count     61353
unique    13704
top       Linux
freq       3793
Name: PlatformDesireNextYear, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:25%; float:left; padding-right:5px; color:blue; font-weight: bold;">
72. <br>FrameworkWorkedWith:
</div>

<div style="margin-left: 25%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Which of the following libraries, frameworks, and tools have you done extensive development work in over the past year, and which do you want to work in over the next year?
</div>

<br>
<div style="width:25%; float:left; padding-right:5px; color:blue; font-weight: bold;">
73. <br>FrameworkDesireNextYear:
</div>

<div style="margin-left: 25%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Which of the following libraries, frameworks, and tools have you done extensive development work in over the past year, and which do you want to work in over the next year?
</div>

In [63]:
columns = list(df.columns.values[71:73])
labels = ["Framework utilizado", "FW deseado próximo año"]

data = []
counter = 72
sorterIndex = {}
for col, label in zip(columns, labels):
    display(HTML('<hr style="border-width: 3px;">'))
    display(HTML('<span style="color:blue; font-weight: bold;">' + str(counter) + ". " + 
                 col + ": " +'</span>' + '<span style="font-weight: bold;">'  + 
                 label +'</span>'))
    print(df[col].describe())

    d = get_counters(df[col].dropna(), label)
    d['Porcentaje'] = d.apply (lambda row: percent (row, col), axis=1)
    display(HTML(d.to_html()))

    if len(sorterIndex) == 0:
        indices = list(d.iloc[:,0])
        sorterIndex = dict(zip(indices, range(len(indices))))
    else:
        # Utilizar el tipo "category" para usarlo como criterio de ordenamiento
        d.iloc[:,0] = d.iloc[:,0].astype("category")
        d.iloc[:,0].cat.set_categories(sorterIndex, inplace=True)
        d = d.sort_values([d.columns[0]])
    counter += 1
        
    data.append(d)
    
fig = get_fig_bar_group(data, labels) 
py.offline.iplot(fig)

count         51620
unique         1014
top       .NET Core
freq           4517
Name: FrameworkWorkedWith, dtype: object


count             55218
unique             1786
top       Node.js;React
freq               3797
Name: FrameworkDesireNextYear, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:10%; float:left; padding-right:5px; color:blue; font-weight: bold;">
74. IDE:
</div>

<div style="margin-left: 10%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Which development environment(s) do you use regularly? Please check all that apply.
</div>
</div>

In [64]:
def get_fig_bubble(data):
    d2 = data[:25]
    d2 = d2.reindex(index=d2.index[::-1])

    size = np.array(d2.iloc[:,2])
    dg = [
        go.Scatter(
            x=d2.iloc[:,0],
            y=d2.iloc[:,1],
            mode='markers',
            marker=dict(color = random_colors(25),size= size)
        )
    ]
    layout = go.Layout(
        title=list(data)[0],
        yaxis=dict(
            title=list(data)[1]
        )
    )
    return go.Figure(data=dg, layout=layout)

In [65]:
print(df['IDE'].describe())

data = get_counters(df['IDE'].dropna(), "IDE utilizado")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'IDE'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_bubble(data)
py.offline.iplot(fig)

count                                75398
unique                                7884
top       Visual Studio;Visual Studio Code
freq                                  2548
Name: IDE, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
75. OperatingSystem:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
What is the primary operating system in which you work?
</div>
</div>

In [66]:
print(df['OperatingSystem'].describe())

data = get_counters(df['OperatingSystem'].dropna(), "Sistema operativo usado")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'OperatingSystem'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data, hole = 0.2, pull = 0.1)
py.offline.iplot(fig)

count       76179
unique          4
top       Windows
freq        38022
Name: OperatingSystem, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
76. NumberMonitors:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
How many monitors are set up at your workstation?
</div>
</div>

In [67]:
print(df['NumberMonitors'].describe())

data = get_counters(df['NumberMonitors'].dropna(), "Número de monitores")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'NumberMonitors'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data)
py.offline.iplot(fig)

count     76398
unique        5
top           2
freq      39063
Name: NumberMonitors, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
77. Methodology:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Which of the following methodologies do you have experience working in?
</div>
</div>

In [68]:
print(df['Methodology'].describe())

data = get_counters(df['Methodology'].dropna(), "Metodologías utilizadas")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'Methodology'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data, hole = 0.2, pull = 0.1)
py.offline.iplot(fig)

count           58981
unique            480
top       Agile;Scrum
freq             9724
Name: Methodology, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
78. VersionControl:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
What version control systems do you use regularly? Please select all that apply.
</div>
</div>

In [69]:
print(df['VersionControl'].describe())

data = get_counters(df['VersionControl'].dropna(), "Manejador de versiones")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'VersionControl'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data, hole = 0.2, pull = 0.1)
py.offline.iplot(fig)

count     74298
unique       90
top         Git
freq      44133
Name: VersionControl, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
79. CheckInCode:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Over the last year, how often have you checked-in or committed code?
</div>
</div>

In [70]:
print(df['CheckInCode'].describe())

data = get_counters(df['CheckInCode'].dropna(), "Actualizaciones de código")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'CheckInCode'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data, hole = 0.2, pull = 0.1)
py.offline.iplot(fig)

count                      72355
unique                         6
top       Multiple times per day
freq                       43566
Name: CheckInCode, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
80. AdBlocker:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Do you have ad-blocking software installed on any computers you use regularly?
</div>
</div>

In [71]:
print(df['AdBlocker'].describe())

data = get_counters(df['AdBlocker'].dropna(), "Utiliza un AdBlocker")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'AdBlocker'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data, hole = 0.2, pull = 0.1)
py.offline.iplot(fig)

count     76055
unique        3
top         Yes
freq      55011
Name: AdBlocker, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
81. AdBlockerDisable:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
In the past month, have you disabled your ad blocker for any reason, even temporarily or for a specific website?
</div>
</div>

In [72]:
print(df['AdBlockerDisable'].describe())

data = get_counters(df['AdBlockerDisable'].dropna(), "Desabilitar AdBlocker")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'AdBlockerDisable'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data, hole = 0.2, pull = 0.1)
py.offline.iplot(fig)

count     54898
unique        3
top         Yes
freq      38798
Name: AdBlockerDisable, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
82. AdBlockerReasons:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
What are the reasons that you have disabled your ad blocker in the past month? Please select all that apply.
</div>
</div>

In [73]:
print(df['AdBlockerReasons'].describe())

data = get_counters(df['AdBlockerReasons'].dropna(), "Razones para desabilitar AdBlocker")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'AdBlockerReasons'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data)
py.offline.iplot(fig)

count                                                                          37745
unique                                                                            63
top       The website I was visiting forced me to disable it to access their content
freq                                                                            7410
Name: AdBlockerReasons, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
83-85. <br>AdsAgreeDisagree1:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
To what extent do you agree or disagree with the following statements: 
<ol>
<li><b>Online advertising can be valuable when it is relevant to me</b>.</li>
<li><b>I enjoy seeing online updates from companies that I like</b>.</li>
<li><b>I fundamentally dislike the concept of advertising</b>.</li>
</ol>
</div>

</div>

In [74]:
columns = list(df.columns.values[82:85])
labels = ["Propaganda valiosa", "Disfruto actualización", "Me desagrada la propaganda"]

data = []
counter = 83
sorterIndex = {}
for col, label in zip(columns, labels):
    display(HTML('<hr style="border-width: 3px;">'))
    display(HTML('<span style="color:blue; font-weight: bold;">' + str(counter) + ". " + 
                 col + ": " +'</span>' + '<span style="font-weight: bold;">'  + 
                 label +'</span>'))
    print(df[col].describe())

    d = get_counters(df[col].dropna(), label)
    d['Porcentaje'] = d.apply (lambda row: percent (row, col), axis=1)
    display(HTML(d.to_html()))

    if len(sorterIndex) == 0:
        indices = list(d.iloc[:,0])
        sorterIndex = dict(zip(indices, range(len(indices))))
    else:
        # Utilizar el tipo "category" para usarlo como criterio de ordenamiento
        d.iloc[:,0] = d.iloc[:,0].astype("category")
        d.iloc[:,0].cat.set_categories(sorterIndex, inplace=True)
        d = d.sort_values([d.columns[0]])
    counter += 1
        
    data.append(d)
    
fig = get_fig_bar_group(data, labels) 
py.offline.iplot(fig)

count              74485
unique                 5
top       Somewhat agree
freq               29875
Name: AdsAgreeDisagree1, dtype: object


count              74413
unique                 5
top       Somewhat agree
freq               27589
Name: AdsAgreeDisagree2, dtype: object


count                          74414
unique                             5
top       Neither agree nor disagree
freq                           22096
Name: AdsAgreeDisagree3, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:15%; float:left; padding-right:5px; color:blue; font-weight: bold;">
86. AdsActions:
</div>

<div style="margin-left: 15%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Which of the following actions have you taken in the past month? Please select all that apply.
</div>
</div>

In [75]:
print(df['AdsActions'].describe())

data = get_counters(df['AdsActions'].dropna(), "Acciones tomadas último mes")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'AdsActions'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data)
py.offline.iplot(fig)

count                                                       59514
unique                                                         15
top       Stopped going to a website because of their advertising
freq                                                        16992
Name: AdsActions, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
87-93. <br>AdsPriorities1 - <br>AdsPriorities7:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Please rank the following advertising qualities in order of their importance to you (by dragging the choices up and down), where 1 is the most important, and 7 is the least important.  
<b>
<ol>
<li>The advertisement is relevant to me.</li>
<li>The advertisement is honest about its goals.</li>
<li>The advertisement provides useful information.</li>
<li>The advertisement seems trustworthy.</li>
<li>The advertisement is from a company that I like.</li>
<li>The advertisement offers something of value, like a free trial.</li>
<li>The advertisement avoids fluffy or vague language.</li>
</ol>
</b>
</div>
</div>

In [76]:
columns = list(df.columns.values[86:93])
labels = ['Relevancia para mi', 'Honestidad sobre sus objetivos', 'Información útil', 
          'Credibilidad', 'Anunciante de interés','Oferta de valor', 
          'Lenguaje simple']

top_labels = []
x_data = []
counter = 87
for col, label in zip(columns, labels):
    display(HTML('<hr style="border-width: 3px;">'))
    display(HTML('<span style="color:blue; font-weight: bold;">' + str(counter) + ". " + 
                 col + ": " +'</span>' + '<span style="font-weight: bold;">'  + 
                 label +'</span>'))
    print(df[col].describe())
    d = get_counters_numeric(df[col].dropna(), label)
    d['Porcentaje'] = d.apply (lambda row: percent (row, col), axis=1)
    display(HTML(d.to_html()))
    
    dsorted = d.sort_values(d.columns[0])
    if len(top_labels) == 0:
        top_labels = list(dsorted.iloc[:,0])
    x_data.append(list(dsorted.iloc[:,1]))
    counter += 1

fig = get_fig_bar_mult(columns, labels, x_data)
    
py.offline.iplot(fig)

count    60479.000000
mean         2.726880
std          1.881078
min          1.000000
25%          1.000000
50%          2.000000
75%          4.000000
max          7.000000
Name: AdsPriorities1, dtype: float64


count    60479.000000
mean         3.805784
std          1.821323
min          1.000000
25%          2.000000
50%          4.000000
75%          5.000000
max          7.000000
Name: AdsPriorities2, dtype: float64


count    60479.000000
mean         3.340945
std          1.673485
min          1.000000
25%          2.000000
50%          3.000000
75%          5.000000
max          7.000000
Name: AdsPriorities3, dtype: float64


count    60479.000000
mean         3.782470
std          1.844864
min          1.000000
25%          2.000000
50%          4.000000
75%          5.000000
max          7.000000
Name: AdsPriorities4, dtype: float64


count    60479.000000
mean         4.383604
std          1.931746
min          1.000000
25%          3.000000
50%          5.000000
75%          6.000000
max          7.000000
Name: AdsPriorities5, dtype: float64


count    60479.000000
mean         5.138809
std          1.853249
min          1.000000
25%          4.000000
50%          6.000000
75%          7.000000
max          7.000000
Name: AdsPriorities6, dtype: float64


count    60479.000000
mean         4.821459
std          1.874895
min          1.000000
25%          3.000000
50%          5.000000
75%          7.000000
max          7.000000
Name: AdsPriorities7, dtype: float64


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:15%; float:left; padding-right:5px; color:blue; font-weight: bold;">
94. AIDangerous:
</div>

<div style="margin-left: 15%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
What do you think is the most dangerous aspect of increasingly advanced AI technology?
</div>
</div>
<br>
<div style="width:100%; overflow:hidden;">
<div style="width:15%; float:left; padding-right:5px; color:blue; font-weight: bold;">
95. AIInteresting:
</div>

<div style="margin-left: 15%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
What do you think is the most exciting aspect of increasingly advanced AI technology?
</div>
</div>

In [77]:
columns = list(df.columns.values[93:95])
labels = ["Aspectos de riesgo", "Aspecto de interés"]

data = []
counter = 94
sorterIndex = {}
for col, label in zip(columns, labels):
    display(HTML('<hr style="border-width: 3px;">'))
    display(HTML('<span style="color:blue; font-weight: bold;">' + str(counter) + ". " + 
                 col + ": " +'</span>' + '<span style="font-weight: bold;">'  + 
                 label +'</span>'))
    print(df[col].describe())

    d = get_counters(df[col].dropna(), label)
    d['Porcentaje'] = d.apply (lambda row: percent (row, col), axis=1)
    display(HTML(d.to_html()))

    if len(sorterIndex) == 0:
        indices = list(d.iloc[:,0])
        sorterIndex = dict(zip(indices, range(len(indices))))
    else:
        # Utilizar el tipo "category" para usarlo como criterio de ordenamiento
        d.iloc[:,0] = d.iloc[:,0].astype("category")
        d.iloc[:,0].cat.set_categories(sorterIndex, inplace=True)
        d = d.sort_values([d.columns[0]])
    counter += 1
        
    data.append(d)
    
fig = get_fig_bar_group(data, labels, option='stack') 
py.offline.iplot(fig)

count                                     63115
unique                                        4
top       Algorithms making important decisions
freq                                      18020
Name: AIDangerous, dtype: object


count                             65367
unique                                4
top       Increasing automation of jobs
freq                              26644
Name: AIInteresting, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
96. AIResponsible:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Whose responsibility is it, primarily, to consider the ramifications of increasingly advanced AI technology?
</div>
</div>

In [78]:
print(df['AIResponsible'].describe())

data = get_counters(df['AIResponsible'].dropna(), 'Responsable')
data['Porcentaje'] = data.apply (lambda row: percent (row, 'AIResponsible'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data, hole = 0.2, pull = 0.1)
py.offline.iplot(fig)

count                                            65553
unique                                               4
top       The developers or the people creating the AI
freq                                             31348
Name: AIResponsible, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:15%; float:left; padding-right:5px; color:blue; font-weight: bold;">
97. AIFuture:
</div>

<div style="margin-left: 15%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Overall, what's your take on the future of artificial intelligence?
</div>
</div>

In [79]:
print(df['AIFuture'].describe())

data = get_counters(df['AIFuture'].dropna(), "Postura sobre futuro de la IA")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'AIFuture'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data)
py.offline.iplot(fig)

count                                                                        69728
unique                                                                           3
top       I'm excited about the possibilities more than worried about the dangers.
freq                                                                         50773
Name: AIFuture, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
98. EthicsChoice:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Imagine that you were asked to write code for a purpose or product that you consider extremely unethical. Do you write the code anyway?
</div>
</div>

In [80]:
print(df['EthicsChoice'].describe())

data = get_counters(df['EthicsChoice'].dropna(), "Codificación de código no ético")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'EthicsChoice'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data)
py.offline.iplot(fig)

count     70782
unique        3
top          No
freq      41441
Name: EthicsChoice, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
99. EthicsReport:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Do you report or otherwise call out the unethical code in question?
</div>
</div>

In [81]:
print(df['EthicsReport'].describe())

data = get_counters(df['EthicsReport'].dropna(), "Denuncia de código no ético")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'EthicsReport'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data, hole = 0.2, pull = 0.1)
py.offline.iplot(fig)

count                     70426
unique                        4
top       Depends on what it is
freq                      32812
Name: EthicsReport, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
100. EthicsResponsible:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Who do you believe is ultimately most responsible for code that accomplishes something unethical?
</div>
</div>

In [82]:
print(df['EthicsResponsible'].describe())

data = get_counters(df['EthicsResponsible'].dropna(), "Responsable de código no ético")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'EthicsResponsible'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data, hole = 0.2, pull = 0.1)
py.offline.iplot(fig)

count                                            64540
unique                                               3
top       Upper management at the company/organization
freq                                             37118
Name: EthicsResponsible, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
101. EthicalImplications:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Do you believe that you have an obligation to consider the ethical implications of the code that you write?
</div>
</div>

In [83]:
print(df['EthicalImplications'].describe())

data = get_counters(df['EthicalImplications'].dropna(), "Consideraciones de ética")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'EthicalImplications'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data, hole = 0.2, pull = 0.1)
py.offline.iplot(fig)

count     69309
unique        3
top         Yes
freq      55200
Name: EthicalImplications, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:25%; float:left; padding-right:5px; color:blue; font-weight: bold;">
102. StackOverflowRecommend:
</div>

<div style="margin-left: 25%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
How likely is it that you would recommend Stack Overflow overall to a friend or colleague? Where 0 is not likely at all and 10 is very likely.
</div>
</div>

In [84]:
print(df['StackOverflowRecommend'].describe())

data = get_counters(df['StackOverflowRecommend'].dropna(), "Recomendar Stack Overflow")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'StackOverflowRecommend'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data, hole = 0.2, pull = 0.1)
py.offline.iplot(fig)

count                76489
unique                  11
top       10 (Very Likely)
freq                 52790
Name: StackOverflowRecommend, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
103. StackOverflowVisit:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
How frequently would you say you visit Stack Overflow?
</div>
</div>

In [85]:
print(df['StackOverflowVisit'].describe())

data = get_counters(df['StackOverflowVisit'].dropna(), 
                    "Frecuencia de visita a Stack Overflow")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'StackOverflowVisit'), axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data, hole = 0.2, pull = 0.1)
py.offline.iplot(fig)

count                     76811
unique                        6
top       Daily or almost daily
freq                      24964
Name: StackOverflowVisit, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:25%; float:left; padding-right:5px; color:blue; font-weight: bold;">
104. StackOverflowHasAccount:
</div>

<div style="margin-left: 25%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Do you have a Stack Overflow account?
</div>
</div>

In [86]:
print(df['StackOverflowHasAccount'].describe())

data = get_counters(df['StackOverflowHasAccount'].dropna(), "Cuenta en Stack Overflow")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'StackOverflowHasAccount'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data, hole = 0.2, pull = 0.1)
py.offline.iplot(fig)

count     76791
unique        3
top         Yes
freq      67146
Name: StackOverflowHasAccount, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:25%; float:left; padding-right:5px; color:blue; font-weight: bold;">
105. StackOverflowParticipate:
</div>

<div style="margin-left: 25%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
How frequently would you say you participate in Q&amp;A on Stack Overflow? By participate we mean ask, answer, vote for, or comment on questions.
</div>
</div>

In [87]:
print(df['StackOverflowParticipate'].describe())

data = get_counters(df['StackOverflowParticipate'].dropna(), "Participación en Q&A")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'StackOverflowParticipate'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data, hole = 0.2, pull = 0.1)
py.offline.iplot(fig)

count                                   65740
unique                                      6
top       Less than once per month or monthly
freq                                    25778
Name: StackOverflowParticipate, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
106. StackOverflowJobs:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Have you ever used or visited Stack Overflow Jobs?
</div>
</div>

In [88]:
print(df['StackOverflowJobs'].describe())

data = get_counters(df['StackOverflowJobs'].dropna(), "Ha visitado Stack Overflow Jobs")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'StackOverflowJobs'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data, hole = 0.2, pull = 0.1)
py.offline.iplot(fig)

count     75297
unique        3
top         Yes
freq      38727
Name: StackOverflowJobs, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:25%; float:left; padding-right:5px; color:blue; font-weight: bold;">
107. StackOverflowDevStory:
</div>

<div style="margin-left: 25%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Do you have an up-to-date Developer Story on Stack Overflow?
</div>
</div>

In [89]:
print(df['StackOverflowDevStory'].describe())

data = get_counters(df['StackOverflowDevStory'].dropna(), "Developer Story actualizada")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'StackOverflowDevStory'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data, hole = 0.2, pull = 0.1)
py.offline.iplot(fig)

count                                 65677
unique                                    4
top       No, and I don't know what that is
freq                                  24019
Name: StackOverflowDevStory, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:30%; float:left; padding-right:5px; color:blue; font-weight: bold;">
108. StackOverflowJobsRecommend:
</div>

<div style="margin-left: 30%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
How likely is it that you would recommend Stack Overflow Jobs to a friend or colleague? Where 0 is not likely at all and 10 is very likely.
</div>
</div>

In [90]:
print(df['StackOverflowJobsRecommend'].describe())

data = get_counters(df['StackOverflowJobsRecommend'].dropna(), 
                    "Recomendar Stack Overflow Jobs")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'StackOverflowJobsRecommend'),
                                 axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data, hole = 0.2, pull = 0.1)
py.offline.iplot(fig)

count                38317
unique                  11
top       10 (Very Likely)
freq                 10137
Name: StackOverflowJobsRecommend, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:30%; float:left; padding-right:5px; color:blue; font-weight: bold;">
109. StackOverflowConsiderMember:
</div>

<div style="margin-left: 30%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Do you consider yourself a member of the Stack Overflow community?
</div>
</div>

In [91]:
print(df['StackOverflowConsiderMember'].describe())

data = get_counters(df['StackOverflowConsiderMember'].dropna(), "Miembro de Stack Overflow")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'StackOverflowConsiderMember'),
                                 axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data, hole = 0.2, pull = 0.1)
py.offline.iplot(fig)

count     76007
unique        3
top         Yes
freq      42146
Name: StackOverflowConsiderMember, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:25%; float:left; padding-right:5px; color:blue; font-weight: bold;">
110-114. <br>HypotheticalTools1 - <br>HypotheticalTools5:
</div>

<div style="margin-left: 25%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Please rate your interest in participating in each of the following hypothetical tools on Stack Overflow, where 1 is not at all interested and 5 is extremely interested.   
<b>
<ol>
<li>A peer mentoring system.</li>
<li>A private area for people new to programming.</li>
<li>A programming-oriented blog platform.</li>
<li>An employer or job review system.</li>
<li>An area for Q&amp;A related to career growth.</li>
</ol>
</b>
</div>
</div>

In [92]:
columns = list(df.columns.values[109:114])
labels = ['Tutoría de pares', 'Área protegida para novatos', 'Paltaforma blog', 
          'Bolsa de trabajo', 'Q&A sobre desarrollo profesional']

top_labels = []
x_data = []
counter = 110
for col, label in zip(columns, labels):
    display(HTML('<hr style="border-width: 3px;">'))
    display(HTML('<span style="color:blue; font-weight: bold;">' + str(counter) + ". " + 
                 col + ": " +'</span>' + '<span style="font-weight: bold;">'  + 
                 label +'</span>'))
    print(df[col].describe())
    d = get_counters_numeric(df[col].dropna(), label)
    d['Porcentaje'] = d.apply (lambda row: percent (row, col), axis=1)
    display(HTML(d.to_html()))
    
    dsorted = d.sort_values(d.columns[0])
    if len(top_labels) == 0:
        top_labels = list(dsorted.iloc[:,0])
    x_data.append(list(dsorted.iloc[:,1]))
    counter += 1

fig = get_fig_bar_mult(columns, labels, x_data, -10)
py.offline.iplot(fig)

count                   70068
unique                      5
top       Somewhat interested
freq                    21315
Name: HypotheticalTools1, dtype: object


count                     70052
unique                        5
top       Not at all interested
freq                      20278
Name: HypotheticalTools2, dtype: object


count                   69999
unique                      5
top       Somewhat interested
freq                    18144
Name: HypotheticalTools3, dtype: object


count               69986
unique                  5
top       Very interested
freq                19133
Name: HypotheticalTools4, dtype: object


count                   70045
unique                      5
top       Somewhat interested
freq                    18004
Name: HypotheticalTools5, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:15%; float:left; padding-right:5px; color:blue; font-weight: bold;">
115. WakeTime:
</div>

<div style="margin-left: 15%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
On days when you work, what time do you typically wake up?
</div>
</div>

In [93]:
print(df['WakeTime'].describe())

data = get_counters(df['WakeTime'].dropna(), "Hora en que se levanta")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'WakeTime'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data, hole = 0.2, pull = 0.1)
py.offline.iplot(fig)

count                      72146
unique                        11
top       Between 7:01 - 8:00 AM
freq                       21250
Name: WakeTime, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
116. HoursComputer:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
On a typical day, how much time do you spend on a desktop or laptop computer?
</div>
</div>

In [94]:
print(df['HoursComputer'].describe())

data = get_counters(df['HoursComputer'].dropna(), "Tiempo en la computadora")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'HoursComputer'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_bar(data)
py.offline.iplot(fig)

count            72133
unique               5
top       9 - 12 hours
freq             37983
Name: HoursComputer, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:15%; float:left; padding-right:5px; color:blue; font-weight: bold;">
117. HoursOutside:
</div>

<div style="margin-left: 15%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
On a typical day, how much time do you spend outside?
</div>
</div>

In [95]:
print(df['HoursOutside'].describe())

data = get_counters(df['HoursOutside'].dropna(), "Horas que pasa en exteriores")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'HoursOutside'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_bar(data)
py.offline.iplot(fig)

count           72024
unique              5
top       1 - 2 hours
freq            27788
Name: HoursOutside, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:15%; float:left; padding-right:5px; color:blue; font-weight: bold;">
118. SkipMeals:
</div>

<div style="margin-left: 15%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
In a typical week, how many times do you skip a meal in order to be more productive?
</div>
</div>

In [96]:
print(df['SkipMeals'].describe())

data = get_counters(df['SkipMeals'].dropna(), "Cuantas veces se salta una comida")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'SkipMeals'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data, hole = 0.2, pull = 0.1)
py.offline.iplot(fig)

count     71946
unique        4
top       Never
freq      45772
Name: SkipMeals, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
119. ErgonomicDevices:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
What ergonomic furniture or devices do you use on a regular basis? Please select all that apply.
</div>
</div>

In [97]:
print(df['ErgonomicDevices'].describe())

data = get_counters(df['ErgonomicDevices'].dropna(), "Dispositivos ergonómicos")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'ErgonomicDevices'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data, hole = 0.2, pull = 0.1)
py.offline.iplot(fig)

count                           34058
unique                             15
top       Ergonomic keyboard or mouse
freq                            10164
Name: ErgonomicDevices, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:15%; float:left; padding-right:5px; color:blue; font-weight: bold;">
120. Exercise:
</div>

<div style="margin-left: 15%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
In a typical week, how many times do you exercise?
</div>
</div>

In [98]:
print(df['Exercise'].describe())

data = get_counters(df['Exercise'].dropna(), "Ejercicio")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'Exercise'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data, hole = 0.2, pull = 0.1)
py.offline.iplot(fig)

count                          72108
unique                             4
top       I don't typically exercise
freq                           26995
Name: Exercise, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:15%; float:left; padding-right:5px; color:blue; font-weight: bold;">
121. Gender:
</div>

<div style="margin-left: 15%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Which of the following do you currently identify as? Please select all that apply. If you prefer not to answer, you may leave this question blank.
</div>
</div>

In [99]:
print(df['Gender'].describe())
data = get_counters(df['Gender'].dropna(), "Género")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'Gender'),axis=1)
display(HTML(data.to_html()))

count     64469
unique       15
top        Male
freq      59458
Name: Gender, dtype: object


Aunque estos resultados parecen "razonables", a primera vista, podemos esperar que haya errores, debido a la confusión de la terminología. Observemos los resultados sin agrupar:

In [100]:
def get_counters_simple(col, label):
    full_list = "|".join(col)
    each_word = full_list.split("|")
    each_word = Counter(each_word).most_common()
    return pd.DataFrame(each_word, columns = [label, "Participantes"])

print(df['Gender'].describe())
data = get_counters_simple(df['Gender'].dropna(), "Género")
display(HTML(data.to_html()))

count     64469
unique       15
top        Male
freq      59458
Name: Gender, dtype: object


<div style="width:100%; overflow:hidden;">
<div style="width:15%; float:left; padding-right:5px; color:red; font-weight: bold;">
Posible error:
</div>

<div style="margin-left: 15%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Como puede apreciarse existe una gran confusión en las respuestas, por ejemplo, hay 128 usuarios que dicen tener una identidad de género *Masculina*, pero también *No binaria*, lo cual es una contradicción aparente (definición de [*No binario*](https://lgbt.foundation/who-we-help/trans-people/non-binary)). Por otra parte, *Non-binary*, *genderqueer* y *gender non-conforming*,  son sinónimos (como se establece en la etiqueta).
</div>
</div>

<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
122. <br>SexualOrientation:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Which of the following do you currently identify as? Please select all that apply. If you prefer not to answer, you may leave this question blank.
</div>
</div>

In [101]:
print(df['SexualOrientation'].describe())
data = get_counters_simple(df['SexualOrientation'].dropna(), "Orientación sexual")
display(HTML(data.to_html()))

data = get_counters(df['SexualOrientation'].dropna(), "Orientación sexual")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'SexualOrientation'),axis=1)
display(HTML('<br>' + data.to_html()))

count                        59765
unique                          14
top       Straight or heterosexual
freq                         55013
Name: SexualOrientation, dtype: object


<div style="width:100%; overflow:hidden;">
<div style="width:15%; float:left; padding-right:5px; color:red; font-weight: bold;">
Posible error:
</div>

<div style="margin-left: 15%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Como era de esperarse, en este caso la confusión es aún mayor. Encontramos, por ejemplo, 60 usuarios que declararon una preferencia *Heterosexual* pero que también declaran tener una orientación *Gay*, *Bisexual* y *Asexual*.
</div>
</div>

<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
123. EducationParents:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
What is the highest level of education received by either of your parents? If you prefer not to answer, you may leave this question blank.
</div>
</div>

In [102]:
print(df['EducationParents'].describe())

data = get_counters(df['EducationParents'].dropna(), "Nivel de estudios de sus padres")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'EducationParents'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data, hole = 0.2, pull = 0.1)
py.offline.iplot(fig)

count                                        61813
unique                                           9
top       Bachelor’s degree (BA, BS, B.Eng., etc.)
freq                                         18090
Name: EducationParents, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:15%; float:left; padding-right:5px; color:blue; font-weight: bold;">
124. RaceEthnicity:
</div>

<div style="margin-left: 15%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Which of the following do you identify as? Please check all that apply. If you prefer not to answer, you may leave this question blank.
</div>
</div>

In [103]:
print(df['RaceEthnicity'].describe())

data = get_counters(df['RaceEthnicity'].dropna(), "ASpectos raciales")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'RaceEthnicity'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data, hole = 0.2, pull = 0.1)
py.offline.iplot(fig)

count                            57473
unique                              71
top       White or of European descent
freq                             40541
Name: RaceEthnicity, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:15%; float:left; padding-right:5px; color:blue; font-weight: bold;">
125. Age:
</div>

<div style="margin-left: 15%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
What is your age? If you prefer not to answer, you may leave this question blank.
</div>
</div>

In [104]:
print(df['Age'].describe())

data = get_counters(df['Age'].dropna(), "Rango de edad")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'Age'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data, hole = 0.2, pull = 0.1)
py.offline.iplot(fig)

count                 64574
unique                    7
top       25 - 34 years old
freq                  31759
Name: Age, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
126. Dependents:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Do you have any children or other dependents that you care for? If you prefer not to answer, you may leave this question blank.
</div>
</div>

In [105]:
print(df['Dependents'].describe())

data = get_counters(df['Dependents'].dropna(), "Dependientes")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'Dependents'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data, hole = 0.2, pull = 0.1)
py.offline.iplot(fig)

count     62596
unique        2
top          No
freq      44478
Name: Dependents, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:20%; float:left; padding-right:5px; color:blue; font-weight: bold;">
127. MilitaryUS:
</div>

<div style="margin-left: 20%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
Are you currently serving or have you ever served in the U.S. Military?
</div>
</div>

In [106]:
print(df['MilitaryUS'].describe())

data = get_counters(df['MilitaryUS'].dropna(), "Miltar USA")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'MilitaryUS'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data, hole = 0.2, pull = 0.1)
py.offline.iplot(fig)

count     15781
unique        2
top          No
freq      15043
Name: MilitaryUS, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:15%; float:left; padding-right:5px; color:blue; font-weight: bold;">
128. SurveyTooLong:
</div>

<div style="margin-left: 15%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
How do you feel about the length of the survey that you just completed?
</div>
</div>

In [107]:
print(df['SurveyTooLong'].describe())

data = get_counters(df['SurveyTooLong'].dropna(), "Longitud del cuestionarios")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'SurveyTooLong'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data, hole = 0.2, pull = 0.1)
py.offline.iplot(fig)

count                                    65941
unique                                       3
top       The survey was an appropriate length
freq                                     33257
Name: SurveyTooLong, dtype: object


<hr style="border-width: 3px;">

<div style="width:100%; overflow:hidden;">
<div style="width:15%; float:left; padding-right:5px; color:blue; font-weight: bold;">
129. SurveyEasy:
</div>

<div style="margin-left: 15%; border: 1px solid #cfcfcf; padding: 8px 12px; border-radius:2px; background-color:#f7f7f7;">
How easy or difficult was this survey to complete?
</div>
</div>

In [108]:
print(df['SurveyEasy'].describe())

data = get_counters(df['SurveyEasy'].dropna(), "Dificultad del cuestionario")
data['Porcentaje'] = data.apply (lambda row: percent (row, 'SurveyEasy'),axis=1)
display(HTML(data.to_html()))

fig = get_fig_pie(data, hole = 0.2, pull = 0.1)
py.offline.iplot(fig)

count             65879
unique                5
top       Somewhat easy
freq              24434
Name: SurveyEasy, dtype: object


<span style="color:#313f9e; font-weight: bold;">Conclusiones:</span>
De este primer análisis, se desprende que hay suficientes datos para trabajar, pero que hay que recodificarlos en un formato más apto para su análisis cuantitativo.

### <span style="color:#313f9e; font-weight: bold;"><a name="verif">Verificación de la calidad de los datos:</a></span>

El problema evidente, en este conjunto de datos, es el de valores faltantes. Para determinar la magnitud del problema, calculamos el porcentaje de valores faltantes en cada columna: Un porcentaje superior al 5% será un problema serio.

In [109]:
missing = {}
for col in df.describe(include='all'):
    missing[col] = 100*sum(pd.isnull(df[col])) / df.shape[0]

In [110]:
from operator import itemgetter
table = sorted(missing.items(), key=itemgetter(1))

data = pd.DataFrame(table, columns=["Columna", "Valores Faltantes (%)"])
display(HTML(data.to_html()))

Dado que los datos son generados de una encuesta con reactivos de opción múltiple, no se espera que haya valores atípicos o fuera de rango.  

Sin embargo, si hay un notable problema de datos inconsistentes, que fueron señalados durante la exploración previa. 

Para detectar otros tipos de patrones, como variables altamente correlacionadas, requerimos primero hacer la recodificación de variables, por lo que dejamos ese análisis para la fase de preparación de los datos.